export const ACTIVITIES = [
  // Level 1: Very Light & Silly
  { level: 1, activity: "Say 'hi' to at least two strangers you meet today." },
  { level: 1, activity: "Give a genuine compliment to a friend or family member." },
  { level: 1, activity: "Try to balance a spoon on your nose for 10 seconds." },
  { level: 1, activity: "Take a picture of something interesting you see on your walk." },
  { level: 1, activity: "Listen to a song from a genre you've never tried before." },
  { level: 1, activity: "Spend 5 minutes stretching." },
  { level: 1, activity: "Draw a silly doodle of your favorite animal." },
  { level: 1, activity: "Write down one thing you are grateful for today." },
  { level: 1, activity: "Watch a short, funny video online." },
  { level: 1, activity: "Smile at yourself in the mirror." },

  { level: 1, activity: "Wear mismatched socks today just for fun." },
  { level: 1, activity: "Name five random objects around you as if they were your pets." },
  { level: 1, activity: "Pretend you’re in a movie for 1 minute and narrate your actions." },
  { level: 1, activity: "Text a random emoji to a friend and see how they respond." },
  { level: 1, activity: "Make up a funny dance move and name it after yourself." },
  { level: 1, activity: "Try to whistle your favorite song." },
  { level: 1, activity: "Give your plant or pet a motivational speech." },
  { level: 1, activity: "Count how many blue things you can see in 30 seconds." },
  { level: 1, activity: "Walk backwards for 10 steps safely." },
  { level: 1, activity: "Invent a nickname for yourself and use it once today." },

  { level: 1, activity: "Try writing your name with your non-dominant hand." },
  { level: 1, activity: "Say something kind to the next person you talk to." },
  { level: 1, activity: "Make a funny face selfie and don’t delete it." },
  { level: 1, activity: "Spend 2 minutes just listening to ambient sounds around you." },
  { level: 1, activity: "Sing one line from your favorite song out loud." },
  { level: 1, activity: "Try doing 10 jumping jacks and then laugh loudly." },
  { level: 1, activity: "Pretend you’re a news reporter and narrate what’s happening right now." },
  { level: 1, activity: "Say thank you to an object that helps you daily (like your phone or mug)." },
  { level: 1, activity: "Do 1 random nice thing for someone today." },
  { level: 1, activity: "Send a random 'hope you’re doing great!' message to a friend." },

  { level: 1, activity: "Take a 5-minute break and stare at the clouds." },
  { level: 1, activity: "Write a silly haiku about your breakfast." },
  { level: 1, activity: "Talk to your reflection as if it’s your best friend." },
  { level: 1, activity: "Do a superhero pose for 10 seconds." },
  { level: 1, activity: "Try imitating an animal sound without laughing." },
  { level: 1, activity: "Invent a new word and define it." },
  { level: 1, activity: "Say your favorite color dramatically, like in a movie." },
  { level: 1, activity: "Take a deep breath and sigh loudly in relief." },
  { level: 1, activity: "Count how many times you smile today." },
  { level: 1, activity: "Dance to the first song that comes up on shuffle." },

  { level: 1, activity: "Draw your mood as a cartoon character." },
  { level: 1, activity: "Describe your day in three random emojis." },
  { level: 1, activity: "Try to make up a short rhyme about something near you." },
  { level: 1, activity: "Say your favorite movie quote out loud." },
  { level: 1, activity: "Look up a random fun fact and share it with someone." },
  { level: 1, activity: "Try doing 5 squats while smiling the whole time." },
  { level: 1, activity: "Wave at yourself in a mirror like you’re meeting you for the first time." },
  { level: 1, activity: "Hum a tune without realizing what song it is." },
  { level: 1, activity: "Write a compliment to yourself on a sticky note." },
  { level: 1, activity: "Try to balance a pencil on your finger." },

  { level: 1, activity: "Say one good thing about your current day." },
  { level: 1, activity: "Take a funny photo using your phone’s timer." },
  { level: 1, activity: "Say your name in slow motion like a movie trailer voice." },
  { level: 1, activity: "Try to walk like a penguin for 10 seconds." },
  { level: 1, activity: "Pretend you’re hosting a cooking show for 1 minute." },
  { level: 1, activity: "Do a random high-five to someone nearby." },
  { level: 1, activity: "Make up a new handshake with a friend." },
  { level: 1, activity: "Say 'good morning' in three different accents." },
  { level: 1, activity: "Snap a picture of the weirdest object near you." },
  { level: 1, activity: "Smile every time you see something red today." },

  { level: 1, activity: "Give yourself a funny award (like 'Best Coffee Drinker 2025')." },
  { level: 1, activity: "Name your favorite snack dramatically as if it’s a celebrity." },
  { level: 1, activity: "Try to guess what your pet or object is 'thinking' right now." },
  { level: 1, activity: "Speak only in song lyrics for 1 minute (if possible)." },
  { level: 1, activity: "Pick a random word and use it five times today." },
  { level: 1, activity: "Clap three times for no reason. Just do it." },
  { level: 1, activity: "Try to wink with both eyes (it’s a blink, but still funny)." },
  { level: 1, activity: "Compliment someone’s outfit today." },
  { level: 1, activity: "Draw a smiley face somewhere unexpected." },
  { level: 1, activity: "Say 'I’m awesome!' out loud once today." },

  { level: 1, activity: "Send a funny GIF to a friend." },
  { level: 1, activity: "Pretend your coffee/tea is a magic potion." },
  { level: 1, activity: "Laugh loudly for 10 seconds (fake or real)." },
  { level: 1, activity: "Say 'yes!' enthusiastically to the next simple thing." },
  { level: 1, activity: "Invent your superhero name and power." },
  { level: 1, activity: "Name your phone like it’s your pet." },
  { level: 1, activity: "Do a small dance move every time someone says 'okay' today." },
  { level: 1, activity: "Say 'thank you' to the weather today, whatever it is." },
  { level: 1, activity: "Take a photo of your happiest face." },
  { level: 1, activity: "Pretend your reflection just complimented you back." },

  // Level 2: Light & Easy
 { level: 2, activity: "Read at least 10 pages of a book." },
  { level: 2, activity: "Go for a 15-minute walk outside." },
  { level: 2, activity: "Tidy up one small area of your room or desk." },
  { level: 2, activity: "Try a simple, new recipe for a snack or drink." },
  { level: 2, activity: "Call or text a friend you haven't spoken to in a while." },
  { level: 2, activity: "Write a short journal entry about your day." },
  { level: 2, activity: "Do a quick 10-minute guided meditation." },
  { level: 2, activity: "Learn how to say 'hello' and 'thank you' in a new language." },
  { level: 2, activity: "Organize the apps on your phone's home screen." },
  { level: 2, activity: "Water your plants or a plant in your neighborhood." },

  // New additions
  { level: 2, activity: "Try making a smoothie with whatever fruits you have." },
  { level: 2, activity: "Write down three things you’re thankful for." },
  { level: 2, activity: "Take a photo of something that makes you smile today." },
  { level: 2, activity: "Clean your shoes or organize your footwear." },
  { level: 2, activity: "Watch a short motivational video or TED talk." },
  { level: 2, activity: "Make your bed neatly and add a personal touch." },
  { level: 2, activity: "Write a kind note to someone you appreciate." },
  { level: 2, activity: "Stretch for 10 minutes after waking up." },
  { level: 2, activity: "Go outside and just breathe deeply for one minute." },
  { level: 2, activity: "Make a to-do list for tomorrow." },

  { level: 2, activity: "Find one thing to donate or give away." },
  { level: 2, activity: "Take a photo of the sky and appreciate its colors." },
  { level: 2, activity: "Try to go one hour without looking at your phone." },
  { level: 2, activity: "Listen to a new podcast episode." },
  { level: 2, activity: "Reorganize your bookshelf or digital files." },
  { level: 2, activity: "Write a small goal you want to achieve this week." },
  { level: 2, activity: "Watch a feel-good movie scene." },
  { level: 2, activity: "Drink an extra glass of water today." },
  { level: 2, activity: "Spend 10 minutes daydreaming about your ideal day." },
  { level: 2, activity: "Send a kind text to a family member." },

  { level: 2, activity: "Spend 5 minutes decluttering your workspace." },
  { level: 2, activity: "Try a new hairstyle or outfit combo." },
  { level: 2, activity: "Plan your meals for tomorrow." },
  { level: 2, activity: "Take a short nap or rest your eyes for 10 minutes." },
  { level: 2, activity: "Write down a happy memory." },
  { level: 2, activity: "Play your favorite old song and dance a bit." },
  { level: 2, activity: "Write one nice sentence about yourself." },
  { level: 2, activity: "Try to cook or brew your drink slower, more mindfully." },
  { level: 2, activity: "Unsubscribe from an email list you never read." },
  { level: 2, activity: "Do a quick digital cleanup (like deleting screenshots)." },

  { level: 2, activity: "Try to compliment three people today." },
  { level: 2, activity: "Write a mini poem about your current mood." },
  { level: 2, activity: "Revisit an old photo album or memory." },
  { level: 2, activity: "Try to drink water before every meal today." },
  { level: 2, activity: "Make a playlist that matches your current mood." },
  { level: 2, activity: "Plan a simple treat for yourself this weekend." },
  { level: 2, activity: "Light a candle or use essential oil to relax." },
  { level: 2, activity: "Write your name using fancy handwriting." },
  { level: 2, activity: "Send a funny meme to a friend." },
  { level: 2, activity: "Try to keep good posture for 10 minutes straight." },

  { level: 2, activity: "Take a walk without headphones and just listen." },
  { level: 2, activity: "Try to identify 5 different bird sounds or plants nearby." },
  { level: 2, activity: "Learn one random fact today." },
  { level: 2, activity: "Compliment a stranger’s outfit or smile." },
  { level: 2, activity: "Make a list of songs that always cheer you up." },
  { level: 2, activity: "Try a mini breathing exercise: 4-7-8 method." },
  { level: 2, activity: "Organize your desktop or downloads folder." },
  { level: 2, activity: "Make yourself a warm or iced drink and enjoy it slowly." },
  { level: 2, activity: "Take a short video of something peaceful." },
  { level: 2, activity: "Rearrange one small area to make it prettier." },

  { level: 2, activity: "Write a note to your future self for next week." },
  { level: 2, activity: "Watch a nature video with relaxing sounds." },
  { level: 2, activity: "Try a new app for mindfulness or journaling." },
  { level: 2, activity: "Draw or sketch something without caring about the result." },
  { level: 2, activity: "Say 'thank you' to three people today." },
  { level: 2, activity: "Try doing one household chore you’ve been avoiding." },
  { level: 2, activity: "Practice smiling more during the day." },
  { level: 2, activity: "Pick a random word and write a short story about it." },
  { level: 2, activity: "Read a random Wikipedia article." },
  { level: 2, activity: "Take a slow walk and count your steps for one minute." },

  { level: 2, activity: "Try writing your thoughts without editing for 5 minutes." },
  { level: 2, activity: "Check in with someone just to say hello." },
  { level: 2, activity: "Clean your glasses, phone, or laptop screen." },
  { level: 2, activity: "Stretch before going to bed." },
  { level: 2, activity: "Draw a small doodle on a sticky note and leave it somewhere visible." },
  { level: 2, activity: "Write a random word on paper and decorate it." },
  { level: 2, activity: "Find one new healthy recipe to try later." },
  { level: 2, activity: "Listen to a full album without skipping songs." },
  { level: 2, activity: "Organize your wallet or purse." },
  { level: 2, activity: "Spend time in silence for 5 minutes." },

  // Level 3: Moderate
  { level: 3, activity: "Try a 30-minute home workout video." },
  { level: 3, activity: "Cook a full meal from a recipe you've never tried before." },
  { level: 3, activity: "Visit a local park or library." },
  { level: 3, activity: "Spend an hour on a hobby you enjoy (e.g., painting, coding, music)." },
  { level: 3, activity: "Deep clean one room in your house." },
  { level: 3, activity: "Watch a documentary on a topic you know nothing about." },
  { level:3, activity: "Plan out your goals for the upcoming week." },
  { level: 3, activity: "Go to a coffee shop and read or people-watch for an hour." },
  { level: 3, activity: "Start a free online course on a subject that interests you." },
  { level: 3, activity: "Write a letter to your future self." },

  { level: 3, activity: "Organize your digital photos or cloud files." },
  { level: 3, activity: "Try to learn a short song on a new instrument." },
  { level: 3, activity: "Spend one hour doing creative writing or journaling." },
  { level: 3, activity: "Plan your meals for the next 3 days." },
  { level: 3, activity: "Visit a local spot you've never been to before." },
  { level: 3, activity: "Repaint or redecorate a small area in your house." },
  { level: 3, activity: "Do a 20-minute yoga or pilates session." },
  { level: 3, activity: "Create a personal playlist for productivity." },
  { level: 3, activity: "Watch an educational video about a new topic." },
  { level: 3, activity: "Write a gratitude letter to someone who helped you." },

  { level: 3, activity: "Revisit your old goals and update them." },
  { level: 3, activity: "Try drawing or painting from a photo reference." },
  { level: 3, activity: "Take a mindful walk — no phone, just observe your surroundings." },
  { level: 3, activity: "Try to cook a dish from another country." },
  { level: 3, activity: "Set up a mini vision board or digital inspiration collage." },
  { level: 3, activity: "Watch a classic movie you’ve never seen before." },
  { level: 3, activity: "Do 30 minutes of reading non-fiction or an article series." },
  { level: 3, activity: "Make a budget plan or review your recent expenses." },
  { level: 3, activity: "Reorganize your workspace or home office." },
  { level: 3, activity: "Plan a fun weekend activity or mini outing." },

  { level: 3, activity: "Listen to a podcast about personal development." },
  { level: 3, activity: "Try to cook without using your phone or recipe for guidance." },
  { level: 3, activity: "Spend time writing down your bucket list." },
  { level: 3, activity: "Try a mindfulness coloring book or app." },
  { level: 3, activity: "Back up your important files." },
  { level: 3, activity: "Read about a country and learn 3 facts about it." },
  { level: 3, activity: "Spend one hour learning a new software or tool." },
  { level: 3, activity: "Take an online quiz about your personality or interests." },
  { level: 3, activity: "Clean your fridge or pantry and organize it." },
  { level: 3, activity: "Go through your wardrobe and pick clothes to donate." },

  { level: 3, activity: "Try to recreate a famous piece of art in your own way." },
  { level: 3, activity: "Spend one hour offline doing something analog." },
  { level: 3, activity: "Write a short story based on a random word." },
  { level: 3, activity: "Try journaling with prompts for reflection." },
  { level: 3, activity: "Learn a basic magic trick or optical illusion." },
  { level: 3, activity: "Try doing your routine backward (change the order)." },
  { level: 3, activity: "Make a creative post or photo collage online." },
  { level: 3, activity: "Try a new board game or puzzle challenge." },
  { level: 3, activity: "Host a small online hangout or game night." },
  { level: 3, activity: "Spend time planning your dream vacation." },

  { level: 3, activity: "Write a review of a movie, song, or restaurant." },
  { level: 3, activity: "Visit a local farmer’s market or thrift shop." },
  { level: 3, activity: "Try to memorize a short poem or quote." },
  { level: 3, activity: "Watch a YouTube tutorial and apply it immediately." },
  { level: 3, activity: "Rearrange your furniture for a new vibe." },
  { level: 3, activity: "Cook a themed dinner (e.g., Italian night, Taco Tuesday)." },
  { level: 3, activity: "Make a mini vlog of your day." },
  { level: 3, activity: "Try learning basic sign language phrases." },
  { level: 3, activity: "Create a 7-day challenge for yourself." },
  { level: 3, activity: "Spend time watching the sunset or sunrise." },

  { level: 3, activity: "Plan a simple social gathering with close friends." },
  { level: 3, activity: "Update your resume or portfolio." },
  { level: 3, activity: "Research something that made you curious as a kid." },
  { level: 3, activity: "Try taking 10 aesthetic photos and editing them." },
  { level: 3, activity: "Spend time gardening or repotting a plant." },
  { level: 3, activity: "Create a short personal reflection video for yourself." },
  { level: 3, activity: "Try cooking using only ingredients you already have." },
  { level: 3, activity: "Host a mini trivia or quiz session with friends." },
  { level: 3, activity: "Take a solo lunch or coffee break outdoors." },
  { level: 3, activity: "Write a list of 10 things you’d love to learn this year." },

  { level: 3, activity: "Spend time offline journaling about your emotions." },
  { level: 3, activity: "Learn one new productivity method (e.g., Pomodoro, Eisenhower)." },
  { level: 3, activity: "Try to recreate your favorite restaurant dish." },
  { level: 3, activity: "Write a short gratitude list before bed." },
  { level: 3, activity: "Create a small DIY decoration for your room." },
  { level: 3, activity: "Take a walk while listening to an audiobook." },
  { level: 3, activity: "Try your hand at origami or paper craft." },
  { level: 3, activity: "Plan a budget for your next purchase goal." },
  { level: 3, activity: "Start reading a new book series." },
  { level: 3, activity: "Spend an hour working on a side project or passion idea." },

  { level: 3, activity: "Find a new favorite coffee or tea place." },
  { level: 3, activity: "Organize your phone’s photo gallery." },
  { level: 3, activity: "Take a self-portrait or creative selfie." },
  { level: 3, activity: "Explore a hobby community online." },
  { level: 3, activity: "Try sketching your dream home or outfit." },
  { level: 3, activity: "Cook dinner for someone else." },
  { level: 3, activity: "Write down a problem and brainstorm 5 solutions." },
  { level: 3, activity: "Listen to music without lyrics and focus on the instruments." },
  { level: 3, activity: "Take a one-hour social media break." },
  { level: 3, activity: "Clean a part of your house you rarely touch (like windowsills)." },

  // Level 4: Challenging
  { level: 4, activity: "Go for a jog or run for at least 2 kilometers (or 1.2 miles)." },
  { level: 4, activity: "Visit a museum or art gallery you've never been to." },
  { level: 4, activity: "Have a 'no-screen' evening for at least 3 hours before bed." },
  { level: 4, activity: "Learn the basics of a new skill, like juggling or a card trick." },
  { level: 4, activity: "Do a major declutter of your closet or a storage area." },
  { level: 4, activity: "Volunteer for a local cause for a couple of hours." },
  { level: 4, activity: "Try to recreate a complex dish you saw on a cooking show." },
  { level: 4, activity: "Start a small DIY project, like building a shelf or painting a piece of furniture." },
  { level: 4, activity: "Take a different route for your commute or daily walk and explore a new area." },
  { level: 4, activity: "Strike up a conversation with a barista or cashier and ask them about their day." },
  { level: 4, activity: "Try cold shower therapy for 5 minutes." },
  { level: 4, activity: "Wake up before sunrise and take photos of the morning light." },
  { level: 4, activity: "Write a gratitude letter to someone and actually send it." },
  { level: 4, activity: "Donate items you haven’t used in over a year." },
  { level: 4, activity: "Go a full day without caffeine." },
  { level: 4, activity: "Learn how to make homemade bread or pasta." },
  { level: 4, activity: "Spend one day without saying anything negative." },
  { level: 4, activity: "Try yoga or stretching for 30 minutes straight." },
  { level: 4, activity: "Create a digital detox plan for a full weekend." },
  { level: 4, activity: "Host a small dinner or coffee night with friends." },
  { level: 4, activity: "Try a minimalist challenge: remove 10 unneeded items from your life." },
  { level: 4, activity: "Spend 2 hours learning about a topic you’ve never explored before." },
  { level: 4, activity: "Take 10 photos of your surroundings that capture your current mood." },
  { level: 4, activity: "Make a homemade gift for someone you care about." },
  { level: 4, activity: "Write a personal manifesto about your beliefs and values." },
  { level: 4, activity: "Take yourself on a 'solo date' to a new café or park." },
  { level: 4, activity: "Try intermittent fasting for a day (if healthy for you)." },
  { level: 4, activity: "Read a self-improvement book and apply one lesson immediately." },
  { level: 4, activity: "Go stargazing and note how you feel watching the night sky." },
  { level: 4, activity: "Watch a documentary about another culture or history." },
  { level: 4, activity: "Practice 20 minutes of mindful breathing or meditation." },
  { level: 4, activity: "Clean your digital life: delete old files, emails, and apps." },
  { level: 4, activity: "Set a financial goal and create a small plan toward it." },
  { level: 4, activity: "Compliment five people sincerely today." },
  { level: 4, activity: "Make a playlist that represents your current life chapter." },
  { level: 4, activity: "Take a break from all sugar for one full day." },
  { level: 4, activity: "Try to learn the basic chords on a musical instrument." },
  { level: 4, activity: "Create a short video about something that inspires you." },
  { level: 4, activity: "Invite someone new to join you for lunch or coffee." },
  { level: 4, activity: "Try a new workout routine you’ve never done before." },
  { level: 4, activity: "Research and implement one eco-friendly habit today." },
  { level: 4, activity: "Cook a full meal for your family or roommates without help." },
  { level: 4, activity: "Write down 10 fears — and choose one to face this week." },
  { level: 4, activity: "Go for a full day without social media notifications." },
  { level: 4, activity: "Take care of a plant or pet for someone else for a day." },
  { level: 4, activity: "Host a board game night or activity gathering." },
  { level: 4, activity: "Try to spend one hour observing people and journaling what you notice." },
  { level: 4, activity: "Challenge yourself to eat only homemade meals today." },
  { level: 4, activity: "Write a story about your dream life in 5 years." },
  { level: 4, activity: "Take 20 minutes to reflect on your achievements this year." },
  { level: 4, activity: "Watch a motivational TED Talk and summarize it in your journal." },

  { level: 4, activity: "Go for a morning jog without using headphones — just listen to nature." },
  { level: 4, activity: "Cook a meal entirely from scratch using only raw ingredients." },
  { level: 4, activity: "Spend an entire day without complaining once." },
  { level: 4, activity: "Take one hour to organize your digital photos and delete duplicates." },
  { level: 4, activity: "Try to go vegetarian for one full day." },
  { level: 4, activity: "Recreate an old childhood photo or memory." },
  { level: 4, activity: "Write down your 10-year dream goals — big or small." },
  { level: 4, activity: "Host or join a book discussion group online or in person." },
  { level: 4, activity: "Revisit a hobby you haven’t done in years." },
  { level: 4, activity: "Make a gratitude jar and fill it with at least 5 notes today." },
  { level: 4, activity: "Unsubscribe from 10 email newsletters or ads." },
  { level: 4, activity: "Try to go the whole day using no plastic items." },
  { level: 4, activity: "Bake something new and share it with neighbors or coworkers." },
  { level: 4, activity: "Write a positive review for a small business you like." },
  { level: 4, activity: "Try to fix or repair something broken at home yourself." },
  { level: 4, activity: "Wake up an hour earlier than usual and enjoy quiet time." },
  { level: 4, activity: "Go to a park and feed the birds or stray cats (safely)." },
  { level: 4, activity: "Do a random act of kindness for a stranger." },
  { level: 4, activity: "Record a short message to your future self using video or audio." },
  { level: 4, activity: "Create a daily affirmation and repeat it 10 times today." },
  { level: 4, activity: "Visit a local farmer’s market or thrift store." },
  { level: 4, activity: "Try to live on a small budget for one day (simulate simplicity)." },
  { level: 4, activity: "Practice mindfulness while eating one meal — no phone, no TV." },
  { level: 4, activity: "Donate blood or register as an organ donor." },
  { level: 4, activity: "Try a new sport you’ve never played before." },
  { level: 4, activity: "Spend a full hour learning about financial literacy." },
  { level: 4, activity: "Take a walk under the rain without an umbrella (if safe)." },
  { level: 4, activity: "Write a handwritten letter to a family member." },
  { level: 4, activity: "Take a long bath or self-care session without any distractions." },
  { level: 4, activity: "Try one full day with no sugar or processed food." },
  { level: 4, activity: "Make a time capsule with items or letters to open in 5 years." },
  { level: 4, activity: "Go on a photography walk and take 20 creative shots." },
  { level: 4, activity: "Delete or archive all unneeded apps on your phone." },
  { level: 4, activity: "Write a poem or song about how your week felt." },
  { level: 4, activity: "Watch a film in a foreign language with subtitles." },
  { level: 4, activity: "Challenge yourself to drink only water all day." },
  { level: 4, activity: "Invite someone you admire for coffee or an online chat." },
  { level: 4, activity: "Take 30 minutes to plan a weekend getaway." },
  { level: 4, activity: "Write your own bucket list of 50 things to do before 50." },
  { level: 4, activity: "Do a 20-minute silent reflection walk." },
  { level: 4, activity: "Reorganize your workspace to boost focus and inspiration." },
  { level: 4, activity: "Try to memorize a short poem or quote and recite it aloud." },
  { level: 4, activity: "Host a small trivia or quiz night for friends or family." },
  { level: 4, activity: "Cook an international dish from a culture you respect." },
  { level: 4, activity: "Create a mood board for your ideal life." },
  { level: 4, activity: "Spend 15 minutes every hour stretching or standing up." },
  { level: 4, activity: "Organize your finances or budgeting system." },
  { level: 4, activity: "Spend 2 hours exploring an area of your city you’ve never been to." },
  { level: 4, activity: "Read an article about a complex topic and summarize it in one paragraph." },
  { level: 4, activity: "Go a full day saying only kind words — even to yourself." },

  // Level 5: Adventurous / Heavy
  { level: 5, activity: "Go on a weekend trip to a new city completely alone." },
  { level: 5, activity: "Try an extreme sport like rock climbing, surfing, or kayaking." },
  { level: 5, activity: "Sleep under the stars for one night (camping or backyard)." },
  { level: 5, activity: "Take a 3-day digital detox — no phone, no internet." },
  { level: 5, activity: "Sign up for a dance class or music lesson for a full month." },
  { level: 5, activity: "Join a local club or group with people you don’t know." },
  { level: 5, activity: "Host a public talk or small community workshop." },
  { level: 5, activity: "Do a 24-hour fast (water only, if healthy and safe for you)." },
  { level: 5, activity: "Wake up at 5 AM for an entire week." },
  { level: 5, activity: "Learn a new skill every day for one week (like typing, juggling, etc.)." },
  { level: 5, activity: "Plan a surprise day for someone special without them knowing." },
  { level: 5, activity: "Take a solo road trip to somewhere you’ve never been." },
  { level: 5, activity: "Start learning a new language and commit for at least 30 days." },
  { level: 5, activity: "Join a volunteer organization and help regularly for a month." },
  { level: 5, activity: "Try living a minimalist lifestyle for a week (use only essentials)." },
  { level: 5, activity: "Create a personal blog or YouTube channel and publish something." },
  { level: 5, activity: "Challenge yourself to talk to 10 new people in one day." },
  { level: 5, activity: "Spend a weekend without electricity — no lights, no tech." },
  { level: 5, activity: "Participate in a 5K, marathon, or cycling event." },
  { level: 5, activity: "Plan and host a charity fundraiser or awareness event." },
  { level: 5, activity: "Take a spontaneous trip — book and go within 24 hours." },
  { level: 5, activity: "Do a complete wardrobe reset — donate everything you don’t wear." },
  { level: 5, activity: "Start writing a book or memoir about your life." },
  { level: 5, activity: "Face one of your biggest fears (heights, stage, rejection, etc.)." },
  { level: 5, activity: "Perform music or art in a public space." },
  { level: 5, activity: "Live in a different city for one week." },
  { level: 5, activity: "Do a full house makeover — rearrange, repaint, or redesign." },
  { level: 5, activity: "Spend a week learning survival or outdoor skills." },
  { level: 5, activity: "Commit to waking up early and journaling every morning for 30 days." },
  { level: 5, activity: "Write and send letters to 10 people who shaped your life." },
  { level: 5, activity: "Cook a complete 3-course meal for friends or family." },
  { level: 5, activity: "Climb a mountain or take a serious hiking trail." },
  { level: 5, activity: "Spend a weekend doing nothing but reading and reflection." },
  { level: 5, activity: "Record and publish your first podcast episode." },
  { level: 5, activity: "Host a theme night or dinner party with a unique concept." },
  { level: 5, activity: "Spend a day exploring your city like a tourist." },
  { level: 5, activity: "Learn to cook one traditional dish from another culture." },
  { level: 5, activity: "Commit to daily exercise for one month straight." },
  { level: 5, activity: "Join a public debate or open mic event." },
  { level: 5, activity: "Take a full-day silence retreat (no speaking, no phone)." },
  { level: 5, activity: "Volunteer for a cause you’ve never supported before." },
  { level: 5, activity: "Create and finish a personal art or video project." },
  { level: 5, activity: "Travel somewhere by train just for the experience." },
  { level: 5, activity: "Spend a night at a beach or mountain alone safely." },
  { level: 5, activity: "Try a zero-waste lifestyle for one full day." },
  { level: 5, activity: "Organize a reunion or surprise event for old friends." },
  { level: 5, activity: "Join a fitness challenge or sports competition." },
  { level: 5, activity: "Learn to play a full song on a musical instrument." },
  { level: 5, activity: "Plant a tree or start a small home garden." },
  { level: 5, activity: "Go a whole day without spending any money." },
  { level: 5, activity: "Take part in a cultural or traditional festival." },
  { level: 5, activity: "Do a photo challenge: take one meaningful picture every hour." },
  { level: 5, activity: "Teach someone a skill you’re good at — for free." },
  { level: 5, activity: "Join a meditation or yoga retreat for a weekend." },
  { level: 5, activity: "Learn basic self-defense techniques." },
  { level: 5, activity: "Organize a local community clean-up event." },
  { level: 5, activity: "Write your life’s top 10 lessons and publish them online." },
  { level: 5, activity: "Go to a concert or live event alone." },
  { level: 5, activity: "Try fasting from all digital devices for 48 hours." },
  { level: 5, activity: "Create a piece of digital art and sell it online." },
  { level: 5, activity: "Sleep in a tent — even if just in your backyard." },
  { level: 5, activity: "Start a new hobby that requires consistent skill practice." },
  { level: 5, activity: "Join a local maker space or creative lab." },
  { level: 5, activity: "Learn the basics of investing or personal finance." },
  { level: 5, activity: "Create your own workout routine and follow it for a week." },
  { level: 5, activity: "Take a photo every day for a month documenting your life." },
  { level: 5, activity: "Read one book a week for a month." },
  { level: 5, activity: "Sleep without an alarm and see when your body naturally wakes up." },
  { level: 5, activity: "Spend a day volunteering at an animal shelter." },
  { level: 5, activity: "Start a creative challenge — draw or write daily for 30 days." },
  { level: 5, activity: "Go vegetarian or vegan for one week." },
  { level: 5, activity: "Learn a completely new type of dance." },
  { level: 5, activity: "Take an online certification course and finish it." },
  { level: 5, activity: "Go hiking or trekking with a small group." },
  { level: 5, activity: "Plan and execute a surprise for a loved one." },
  { level: 5, activity: "Do a random act of kindness every day for a week." },
  { level: 5, activity: "Travel to a remote area and disconnect fully." },
  { level: 5, activity: "Participate in a talent show or competition." },
  { level: 5, activity: "Spend 3 days journaling your thoughts and emotions." },
  { level: 5, activity: "Host a workshop or webinar sharing your skills." },
  { level: 5, activity: "Build or make something from scratch (e.g., furniture, app, art)." },
  { level: 5, activity: "Go skydiving, bungee jumping, or ziplining (if available)." },
  { level: 5, activity: "Complete a 7-day gratitude challenge." },
  { level: 5, activity: "Write and send thank-you notes to 5 people." },
  { level: 5, activity: "Visit a new country or region." },
  { level: 5, activity: "Spend one day mentoring or tutoring someone younger." },
  { level: 5, activity: "Try a 24-hour creative marathon — write, draw, or code nonstop." },
  { level: 5, activity: "Create a morning ritual that energizes you every day." },
  { level: 5, activity: "Adopt a pet or foster an animal in need." },
  { level: 5, activity: "Spend a day outdoors with no set plan — just follow curiosity." },
  { level: 5, activity: "Try being a tourist in your own city for an entire day." },
  { level: 5, activity: "Run a personal experiment: change one habit for a month." },
  { level: 5, activity: "Create a short film or documentary." },
  { level: 5, activity: "Plan and lead a hiking group or outdoor meetup." },
  { level: 5, activity: "Spend 48 hours without using your native language." },
  { level: 5, activity: "Challenge yourself to smile at everyone you meet today." },
  { level: 5, activity: "Commit to journaling every night for 30 days." },
  { level: 5, activity: "Take a self-improvement course and apply what you learn." },
  { level: 5, activity: "Face a fear that has been holding you back for years." }
];
