export type ChemicalElement = {
  name: string;
  symbol: string;
  atomicNumber: number;
  atomicMass: number;
  category: string;
  group: number;
  period: number;
  block: string;
  electronConfiguration: string;
  summary: string;
  discovered_by: string;
  named_by: string | null;
  appearance: string | null;
  phase: 'Gas' | 'Liquid' | 'Solid';
  source: string; // URL to wikipedia
  color: string; // Hex color for category
};

export const CHEMICAL_ELEMENTS: ChemicalElement[] = [
  {
    "atomicNumber": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "atomicMass": 1.008,
    "category": "diatomic-nonmetal",
    "group": 1,
    "period": 1,
    "block": "s",
    "electronConfiguration": "1s1",
    "summary": "Hydrogen is the most abundant chemical element in the universe, constituting roughly 75% of all baryonic mass. It is a colorless, odorless, tasteless, non-toxic, and highly combustible diatomic gas with the molecular formula H₂.",
    "discovered_by": "Henry Cavendish",
    "named_by": "Antoine Lavoisier",
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Hydrogen",
    "color": "#a8ffc1"
  },
  {
    "atomicNumber": 2,
    "symbol": "He",
    "name": "Helium",
    "atomicMass": 4.0026,
    "category": "noble-gas",
    "group": 18,
    "period": 1,
    "block": "s",
    "electronConfiguration": "1s2",
    "summary": "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.",
    "discovered_by": "Pierre Janssen & Norman Lockyer",
    "named_by": null,
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Helium",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 3,
    "symbol": "Li",
    "name": "Lithium",
    "atomicMass": 6.94,
    "category": "alkali-metal",
    "group": 1,
    "period": 2,
    "block": "s",
    "electronConfiguration": "[He] 2s1",
    "summary": "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the least dense solid element.",
    "discovered_by": "Johan August Arfwedson",
    "named_by": null,
    "appearance": "silvery-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lithium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "atomicMass": 9.0122,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 2,
    "block": "s",
    "electronConfiguration": "[He] 2s2",
    "summary": "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    "discovered_by": "Louis Nicolas Vauquelin",
    "named_by": null,
    "appearance": "white-gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Beryllium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 5,
    "symbol": "B",
    "name": "Boron",
    "atomicMass": 10.81,
    "category": "metalloid",
    "group": 13,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p1",
    "summary": "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar System.",
    "discovered_by": "Joseph Louis Gay-Lussac",
    "named_by": null,
    "appearance": "black-brown",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Boron",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 6,
    "symbol": "C",
    "name": "Carbon",
    "atomicMass": 12.011,
    "category": "polyatomic-nonmetal",
    "group": 14,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p2",
    "summary": "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "black (graphite), transparent (diamond)",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Carbon",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "atomicMass": 14.007,
    "category": "diatomic-nonmetal",
    "group": 15,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p3",
    "summary": "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    "discovered_by": "Daniel Rutherford",
    "named_by": "Jean-Antoine Chaptal",
    "appearance": "colorless gas, liquid or solid",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Nitrogen",
    "color": "#a8ffc1"
  },
  {
    "atomicNumber": 8,
    "symbol": "O",
    "name": "Oxygen",
    "atomicMass": 15.999,
    "category": "diatomic-nonmetal",
    "group": 16,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p4",
    "summary": "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent.",
    "discovered_by": "Carl Wilhelm Scheele & Joseph Priestley",
    "named_by": "Antoine Lavoisier",
    "appearance": "colorless gas, pale blue liquid",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Oxygen",
    "color": "#a8ffc1"
  },
  {
    "atomicNumber": 9,
    "symbol": "F",
    "name": "Fluorine",
    "atomicMass": 18.998,
    "category": "halogen",
    "group": 17,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p5",
    "summary": "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.",
    "discovered_by": "Henri Moissan",
    "named_by": null,
    "appearance": "pale yellow gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Fluorine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 10,
    "symbol": "Ne",
    "name": "Neon",
    "atomicMass": 20.180,
    "category": "noble-gas",
    "group": 18,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p6",
    "summary": "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions.",
    "discovered_by": "Morris Travers, William Ramsay",
    "named_by": null,
    "appearance": "colorless gas showing glow",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Neon",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 11,
    "symbol": "Na",
    "name": "Sodium",
    "atomicMass": 22.990,
    "category": "alkali-metal",
    "group": 1,
    "period": 3,
    "block": "s",
    "electronConfiguration": "[Ne] 3s1",
    "summary": "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "silvery white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Sodium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicMass": 24.305,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 3,
    "block": "s",
    "electronConfiguration": "[Ne] 3s2",
    "summary": "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals).",
    "discovered_by": "Joseph Black",
    "named_by": null,
    "appearance": "shiny grey solid",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Magnesium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 13,
    "symbol": "Al",
    "name": "Aluminium",
    "atomicMass": 26.982,
    "category": "post-transition-metal",
    "group": 13,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p1",
    "summary": "Aluminium is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, non-magnetic and ductile metal in the boron group.",
    "discovered_by": "Hans Christian Ørsted",
    "named_by": null,
    "appearance": "silvery-gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Aluminium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 14,
    "symbol": "Si",
    "name": "Silicon",
    "atomicMass": 28.085,
    "category": "metalloid",
    "group": 14,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p2",
    "summary": "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard, brittle crystalline solid with a blue-grey metallic lustre, and is a tetravalent metalloid and semiconductor.",
    "discovered_by": "Jöns Jacob Berzelius",
    "named_by": null,
    "appearance": "crystalline, reflective with bluish-tinged faces",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Silicon",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "atomicMass": 30.974,
    "category": "polyatomic-nonmetal",
    "group": 15,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p3",
    "summary": "Phosphorus is a chemical element with symbol P and atomic number 15. Elemental phosphorus exists in two major forms, white phosphorus and red phosphorus.",
    "discovered_by": "Hennig Brand",
    "named_by": null,
    "appearance": "colorless, waxy white, yellow, scarlet, red, violet, black",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Phosphorus",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 16,
    "symbol": "S",
    "name": "Sulfur",
    "atomicMass": 32.06,
    "category": "polyatomic-nonmetal",
    "group": 16,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p4",
    "summary": "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent and nonmetallic.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lemon yellow sintered microcrystals",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Sulfur",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicMass": 35.45,
    "category": "halogen",
    "group": 17,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p5",
    "summary": "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table.",
    "discovered_by": "Carl Wilhelm Scheele",
    "named_by": null,
    "appearance": "pale yellow-green gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Chlorine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 18,
    "symbol": "Ar",
    "name": "Argon",
    "atomicMass": 39.948,
    "category": "noble-gas",
    "group": 18,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p6",
    "summary": "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas.",
    "discovered_by": "Lord Rayleigh, William Ramsay",
    "named_by": null,
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Argon",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 19,
    "symbol": "K",
    "name": "Potassium",
    "atomicMass": 39.098,
    "category": "alkali-metal",
    "group": 1,
    "period": 4,
    "block": "s",
    "electronConfiguration": "[Ar] 4s1",
    "summary": "Potassium is a chemical element with symbol K and atomic number 19. It is a silvery-white metal that is soft enough to be cut with a knife with little force.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "silvery-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Potassium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "atomicMass": 40.078,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 4,
    "block": "s",
    "electronConfiguration": "[Ar] 4s2",
    "summary": "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "dull gray, silver",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Calcium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "atomicMass": 44.956,
    "category": "transition-metal",
    "group": 3,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d1 4s2",
    "summary": "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element.",
    "discovered_by": "Lars Fredrik Nilson",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Scandium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "atomicMass": 47.867,
    "category": "transition-metal",
    "group": 4,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d2 4s2",
    "summary": "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength.",
    "discovered_by": "William Gregor",
    "named_by": "Martin Heinrich Klaproth",
    "appearance": "silvery grey-white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Titanium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 23,
    "symbol": "V",
    "name": "Vanadium",
    "atomicMass": 50.942,
    "category": "transition-metal",
    "group": 5,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d3 4s2",
    "summary": "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, malleable transition metal.",
    "discovered_by": "Andrés Manuel del Río",
    "named_by": "Nils Gabriel Sefström",
    "appearance": "blue-silver-grey metal",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Vanadium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "atomicMass": 51.996,
    "category": "transition-metal",
    "group": 6,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d5 4s1",
    "summary": "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6.",
    "discovered_by": "Louis Nicolas Vauquelin",
    "named_by": null,
    "appearance": "silvery metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Chromium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "atomicMass": 54.938,
    "category": "transition-metal",
    "group": 7,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d5 4s2",
    "summary": "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.",
    "discovered_by": "Johan Gadolin",
    "named_by": null,
    "appearance": "silvery metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Manganese",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 26,
    "symbol": "Fe",
    "name": "Iron",
    "atomicMass": 55.845,
    "category": "transition-metal",
    "group": 8,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d6 4s2",
    "summary": "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lustrous metallic with a grayish tinge",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Iron",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "atomicMass": 58.933,
    "category": "transition-metal",
    "group": 9,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d7 4s2",
    "summary": "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form.",
    "discovered_by": "Georg Brandt",
    "named_by": null,
    "appearance": "hard lustrous gray metal",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Cobalt",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "atomicMass": 58.693,
    "category": "transition-metal",
    "group": 10,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d8 4s2",
    "summary": "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.",
    "discovered_by": "Axel Fredrik Cronstedt",
    "named_by": null,
    "appearance": "lustrous, metallic, and silver with a gold tinge",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Nickel",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 29,
    "symbol": "Cu",
    "name": "Copper",
    "atomicMass": 63.546,
    "category": "transition-metal",
    "group": 11,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d10 4s1",
    "summary": "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "red-orange metallic luster",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Copper",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "atomicMass": 65.38,
    "category": "transition-metal",
    "group": 12,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d10 4s2",
    "summary": "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table.",
    "discovered_by": "Andreas Sigismund Marggraf",
    "named_by": null,
    "appearance": "silver-gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Zinc",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "atomicMass": 69.723,
    "category": "post-transition-metal",
    "group": 13,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p1",
    "summary": "Gallium is a chemical element with symbol Ga and atomic number 31. It is in group 13 of the periodic table.",
    "discovered_by": "Lecoq de Boisbaudran",
    "named_by": null,
    "appearance": "silver-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Gallium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "atomicMass": 72.630,
    "category": "metalloid",
    "group": 14,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p2",
    "summary": "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard-brittle, grayish-white metalloid in the carbon group.",
    "discovered_by": "Clemens Winkler",
    "named_by": null,
    "appearance": "grayish-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Germanium",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 33,
    "symbol": "As",
    "name": "Arsenic",
    "atomicMass": 74.922,
    "category": "metalloid",
    "group": 15,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p3",
    "summary": "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals.",
    "discovered_by": "Albertus Magnus",
    "named_by": null,
    "appearance": "metallic grey",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Arsenic",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 34,
    "symbol": "Se",
    "name": "Selenium",
    "atomicMass": 78.96,
    "category": "polyatomic-nonmetal",
    "group": 16,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p4",
    "summary": "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between the elements above and below in the periodic table.",
    "discovered_by": "Jöns Jacob Berzelius",
    "named_by": null,
    "appearance": "black, red, and gray (not allotropes)",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Selenium",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 35,
    "symbol": "Br",
    "name": "Bromine",
    "atomicMass": 79.904,
    "category": "halogen",
    "group": 17,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p5",
    "summary": "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen.",
    "discovered_by": "Antoine Jérôme Balard",
    "named_by": null,
    "appearance": "red-brown liquid / gas",
    "phase": "Liquid",
    "source": "https://en.wikipedia.org/wiki/Bromine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "atomicMass": 83.798,
    "category": "noble-gas",
    "group": 18,
    "period": 4,
    "block": "p",
    "electronConfiguration": "[Ar] 3d10 4s2 4p6",
    "summary": "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements.",
    "discovered_by": "William Ramsay, Morris Travers",
    "named_by": null,
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Krypton",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "atomicMass": 85.468,
    "category": "alkali-metal",
    "group": 1,
    "period": 5,
    "block": "s",
    "electronConfiguration": "[Kr] 5s1",
    "summary": "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group.",
    "discovered_by": "Robert Bunsen, Gustav Kirchhoff",
    "named_by": null,
    "appearance": "grey white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Rubidium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "atomicMass": 87.62,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 5,
    "block": "s",
    "electronConfiguration": "[Kr] 5s2",
    "summary": "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element.",
    "discovered_by": "William Cruickshank",
    "named_by": null,
    "appearance": "silvery-white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Strontium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "atomicMass": 88.906,
    "category": "transition-metal",
    "group": 3,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d1 5s2",
    "summary": "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides.",
    "discovered_by": "Johan Gadolin",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Yttrium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "atomicMass": 91.224,
    "category": "transition-metal",
    "group": 4,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d2 5s2",
    "summary": "Zirconium is a chemical element with symbol Zr and atomic number 40. The name of zirconium is taken from the name of the mineral zircon.",
    "discovered_by": "Martin Heinrich Klaproth",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Zirconium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "atomicMass": 92.906,
    "category": "transition-metal",
    "group": 5,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d4 5s1",
    "summary": "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, crystalline, ductile transition metal.",
    "discovered_by": "Charles Hatchett",
    "named_by": null,
    "appearance": "gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Niobium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "atomicMass": 95.95,
    "category": "transition-metal",
    "group": 6,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d5 5s1",
    "summary": "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum.",
    "discovered_by": "Carl Wilhelm Scheele",
    "named_by": null,
    "appearance": "gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Molybdenum",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "atomicMass": 98,
    "category": "transition-metal",
    "group": 7,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d5 5s2",
    "summary": "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive.",
    "discovered_by": "Emilio Segrè, Carlo Perrier",
    "named_by": null,
    "appearance": "shiny gray metal",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Technetium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "atomicMass": 101.07,
    "category": "transition-metal",
    "group": 8,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d7 5s1",
    "summary": "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group.",
    "discovered_by": "Karl Karlovich Klaus",
    "named_by": null,
    "appearance": "silvery white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Ruthenium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "atomicMass": 102.91,
    "category": "transition-metal",
    "group": 9,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d8 5s1",
    "summary": "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, and chemically inert transition metal.",
    "discovered_by": "William Hyde Wollaston",
    "named_by": null,
    "appearance": "silvery white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Rhodium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "atomicMass": 106.42,
    "category": "transition-metal",
    "group": 10,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d10",
    "summary": "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803.",
    "discovered_by": "William Hyde Wollaston",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Palladium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 47,
    "symbol": "Ag",
    "name": "Silver",
    "atomicMass": 107.87,
    "category": "transition-metal",
    "group": 11,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d10 5s1",
    "summary": "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lustrous white metal",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Silver",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "atomicMass": 112.41,
    "category": "transition-metal",
    "group": 12,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d10 5s2",
    "summary": "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, bluish-white metal is chemically similar to the two other stable metals in group 12.",
    "discovered_by": "Friedrich Stromeyer",
    "named_by": null,
    "appearance": "silvery bluish-gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Cadmium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 49,
    "symbol": "In",
    "name": "Indium",
    "atomicMass": 114.82,
    "category": "post-transition-metal",
    "group": 13,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p1",
    "summary": "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that is rare in Earth's crust.",
    "discovered_by": "Ferdinand Reich, Hieronymous Theodor Richter",
    "named_by": null,
    "appearance": "silvery lustrous gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Indium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 50,
    "symbol": "Sn",
    "name": "Tin",
    "atomicMass": 118.71,
    "category": "post-transition-metal",
    "group": 14,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p2",
    "summary": "Tin is a chemical element with the symbol Sn and atomic number 50. It is a silvery metal that characteristically has a faint yellow hue.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "silvery-white (beta) or gray (alpha)",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Tin",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "atomicMass": 121.76,
    "category": "metalloid",
    "group": 15,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p3",
    "summary": "Antimony is a chemical element with symbol Sb and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "silvery lustrous gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Antimony",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "atomicMass": 127.60,
    "category": "metalloid",
    "group": 16,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p4",
    "summary": "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.",
    "discovered_by": "Franz-Joseph Müller von Reichenstein",
    "named_by": null,
    "appearance": "silvery lustrous gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Tellurium",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 53,
    "symbol": "I",
    "name": "Iodine",
    "atomicMass": 126.90,
    "category": "halogen",
    "group": 17,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p5",
    "summary": "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a semi-lustrous, non-metallic solid.",
    "discovered_by": "Bernard Courtois",
    "named_by": "Joseph Louis Gay-Lussac",
    "appearance": "lustrous metallic gray, violet as a gas",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Iodine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "atomicMass": 131.29,
    "category": "noble-gas",
    "group": 18,
    "period": 5,
    "block": "p",
    "electronConfiguration": "[Kr] 4d10 5s2 5p6",
    "summary": "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere.",
    "discovered_by": "William Ramsay, Morris Travers",
    "named_by": null,
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Xenon",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 55,
    "symbol": "Cs",
    "name": "Caesium",
    "atomicMass": 132.91,
    "category": "alkali-metal",
    "group": 1,
    "period": 6,
    "block": "s",
    "electronConfiguration": "[Xe] 6s1",
    "summary": "Caesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C.",
    "discovered_by": "Robert Bunsen, Gustav Kirchhoff",
    "named_by": null,
    "appearance": "silvery gold",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Cesium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 56,
    "symbol": "Ba",
    "name": "Barium",
    "atomicMass": 137.33,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 6,
    "block": "s",
    "electronConfiguration": "[Xe] 6s2",
    "summary": "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal.",
    "discovered_by": "Carl Wilhelm Scheele",
    "named_by": null,
    "appearance": "silvery gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Barium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "atomicMass": 138.91,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 5d1 6s2",
    "summary": "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes slowly when exposed to air.",
    "discovered_by": "Carl Gustaf Mosander",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lanthanum",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "atomicMass": 140.12,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f1 5d1 6s2",
    "summary": "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile, and silvery-white metal that tarnishes when exposed to air.",
    "discovered_by": "Martin Heinrich Klaproth",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Cerium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "atomicMass": 140.91,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f3 6s2",
    "summary": "Praseodymium is a chemical element with symbol Pr and atomic number 59. Praseodymium is a soft, silvery, malleable and ductile metal in the lanthanide group.",
    "discovered_by": "Carl Auer von Welsbach",
    "named_by": null,
    "appearance": "grayish white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Praseodymium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "atomicMass": 144.24,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f4 6s2",
    "summary": "Neodymium is a chemical element with symbol Nd and atomic number 60. Neodymium is a soft, silvery metal that tarnishes in air.",
    "discovered_by": "Carl Auer von Welsbach",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Neodymium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "atomicMass": 145,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f5 6s2",
    "summary": "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is extremely rare, with only about 500-600 grams naturally occurring in Earth's crust at any given time.",
    "discovered_by": "Chien Shiung Wu",
    "named_by": null,
    "appearance": "metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Promethium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "atomicMass": 150.36,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f6 6s2",
    "summary": "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air.",
    "discovered_by": "Lecoq de Boisbaudran",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Samarium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 63,
    "symbol": "Eu",
    "name": "Europium",
    "atomicMass": 151.96,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f7 6s2",
    "summary": "Europium is a chemical element with symbol Eu and atomic number 63. Europium is the most reactive lanthanide element, having to be stored under an inert fluid to protect it from atmospheric oxygen or moisture.",
    "discovered_by": "Eugène-Anatole Demarçay",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Europium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "atomicMass": 157.25,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f7 5d1 6s2",
    "summary": "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white metal when oxidation is removed.",
    "discovered_by": "Jean Charles Galissard de Marignac",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Gadolinium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "atomicMass": 158.93,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f9 6s2",
    "summary": "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife.",
    "discovered_by": "Carl Gustaf Mosander",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Terbium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "atomicMass": 162.50,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f10 6s2",
    "summary": "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.",
    "discovered_by": "Lecoq de Boisbaudran",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Dysprosium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "atomicMass": 164.93,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f11 6s2",
    "summary": "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare earth element.",
    "discovered_by": "Marc Delafontaine",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Holmium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 68,
    "symbol": "Er",
    "name": "Erbium",
    "atomicMass": 167.26,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f12 6s2",
    "summary": "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.",
    "discovered_by": "Carl Gustaf Mosander",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Erbium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "atomicMass": 168.93,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f13 6s2",
    "summary": "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series.",
    "discovered_by": "Per Teodor Cleve",
    "named_by": null,
    "appearance": "silvery gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Thulium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "atomicMass": 173.05,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "f",
    "electronConfiguration": "[Xe] 4f14 6s2",
    "summary": "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series.",
    "discovered_by": "Jean Charles Galissard de Marignac",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Ytterbium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "atomicMass": 174.97,
    "category": "lanthanide",
    "group": 3,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d1 6s2",
    "summary": "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air.",
    "discovered_by": "Georges Urbain",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lutetium",
    "color": "#ffbfff"
  },
  {
    "atomicNumber": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "atomicMass": 178.49,
    "category": "transition-metal",
    "group": 4,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d2 6s2",
    "summary": "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.",
    "discovered_by": "Dirk Coster",
    "named_by": null,
    "appearance": "steel gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Hafnium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "atomicMass": 180.95,
    "category": "transition-metal",
    "group": 5,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d3 6s2",
    "summary": "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, it is named after Tantalus from Greek mythology.",
    "discovered_by": "Anders Gustaf Ekeberg",
    "named_by": null,
    "appearance": "gray blue",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Tantalum",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 74,
    "symbol": "W",
    "name": "Tungsten",
    "atomicMass": 183.84,
    "category": "transition-metal",
    "group": 6,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d4 6s2",
    "summary": "Tungsten, also known as wolfram, is a chemical element with symbol W and atomic number 74. Tungsten is a rare metal found naturally on Earth almost exclusively generally in chemical compounds.",
    "discovered_by": "Fausto Elhuyar",
    "named_by": null,
    "appearance": "grayish white, lustrous",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Tungsten",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "atomicMass": 186.21,
    "category": "transition-metal",
    "group": 7,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d5 6s2",
    "summary": "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-gray, heavy, third-row transition metal in group 7 of the periodic table.",
    "discovered_by": "Masataka Ogawa",
    "named_by": "Walter Noddack",
    "appearance": "silvery-grayish",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Rhenium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 76,
    "symbol": "Os",
    "name": "Osmium",
    "atomicMass": 190.23,
    "category": "transition-metal",
    "group": 8,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d6 6s2",
    "summary": "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.",
    "discovered_by": "Smithson Tennant",
    "named_by": null,
    "appearance": "silvery, blue cast",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Osmium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "atomicMass": 192.22,
    "category": "transition-metal",
    "group": 9,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d7 6s2",
    "summary": "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is considered to be the second-densest element.",
    "discovered_by": "Smithson Tennant",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Iridium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "atomicMass": 195.08,
    "category": "transition-metal",
    "group": 10,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d9 6s1",
    "summary": "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silver-white transition metal.",
    "discovered_by": "Antonio de Ulloa",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Platinum",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 79,
    "symbol": "Au",
    "name": "Gold",
    "atomicMass": 196.97,
    "category": "transition-metal",
    "group": 11,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d10 6s1",
    "summary": "Gold is a chemical element with symbol Au and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "metallic yellow",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Gold",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "atomicMass": 200.59,
    "category": "transition-metal",
    "group": 12,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2",
    "summary": "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "silvery",
    "phase": "Liquid",
    "source": "https://en.wikipedia.org/wiki/Mercury_(element)",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "atomicMass": 204.38,
    "category": "post-transition-metal",
    "group": 13,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
    "summary": "Thallium is a chemical element with symbol Tl and atomic number 81. This soft gray post-transition metal is not found free in nature.",
    "discovered_by": "William Crookes",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Thallium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 82,
    "symbol": "Pb",
    "name": "Lead",
    "atomicMass": 207.2,
    "category": "post-transition-metal",
    "group": 14,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
    "summary": "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "metallic gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lead",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "atomicMass": 208.98,
    "category": "post-transition-metal",
    "group": 15,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
    "summary": "Bismuth is a chemical element with symbol Bi and atomic number 83. Bismuth, a pentavalent post-transition metal and one of the pnictogens, chemically resembles its lighter homologs arsenic and antimony.",
    "discovered_by": "Claude François Geoffroy",
    "named_by": null,
    "appearance": "lustrous silver",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Bismuth",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 84,
    "symbol": "Po",
    "name": "Polonium",
    "atomicMass": 209,
    "category": "post-transition-metal",
    "group": 16,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
    "summary": "Polonium is a chemical element with symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes.",
    "discovered_by": "Pierre Curie, Marie Curie",
    "named_by": null,
    "appearance": "silvery",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Polonium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 85,
    "symbol": "At",
    "name": "Astatine",
    "atomicMass": 210,
    "category": "halogen",
    "group": 17,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
    "summary": "Astatine is a radioactive chemical element with symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust.",
    "discovered_by": "Dale R. Corson",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Astatine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 86,
    "symbol": "Rn",
    "name": "Radon",
    "atomicMass": 222,
    "category": "noble-gas",
    "group": 18,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
    "summary": "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.",
    "discovered_by": "Friedrich Ernst Dorn",
    "named_by": null,
    "appearance": "colorless gas, pseudo-solid",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Radon",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 87,
    "symbol": "Fr",
    "name": "Francium",
    "atomicMass": 223,
    "category": "alkali-metal",
    "group": 1,
    "period": 7,
    "block": "s",
    "electronConfiguration": "[Rn] 7s1",
    "summary": "Francium is a chemical element with symbol Fr and atomic number 87. It is extremely radioactive.",
    "discovered_by": "Marguerite Perey",
    "named_by": null,
    "appearance": "metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Francium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 88,
    "symbol": "Ra",
    "name": "Radium",
    "atomicMass": 226,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 7,
    "block": "s",
    "electronConfiguration": "[Rn] 7s2",
    "summary": "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.",
    "discovered_by": "Pierre Curie, Marie Curie",
    "named_by": null,
    "appearance": "silvery white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Radium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "atomicMass": 227,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 6d1 7s2",
    "summary": "Actinium is a radioactive chemical element with symbol Ac and atomic number 89. It was discovered in 1899 by André-Louis Debierne.",
    "discovered_by": "André-Louis Debierne",
    "named_by": null,
    "appearance": "silvery",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Actinium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 90,
    "symbol": "Th",
    "name": "Thorium",
    "atomicMass": 232.04,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 6d2 7s2",
    "summary": "Thorium is a chemical element with symbol Th and atomic number 90. A radioactive actinide metal, thorium is one of only two significantly radioactive elements that still occur naturally in large quantities.",
    "discovered_by": "Jöns Jacob Berzelius",
    "named_by": null,
    "appearance": "silvery, lustrous",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Thorium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "atomicMass": 231.04,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f2 6d1 7s2",
    "summary": "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.",
    "discovered_by": "William Crookes",
    "named_by": "Otto Hahn",
    "appearance": "bright, shiny, silvery",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Protactinium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 92,
    "symbol": "U",
    "name": "Uranium",
    "atomicMass": 238.03,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f3 6d1 7s2",
    "summary": "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table.",
    "discovered_by": "Martin Heinrich Klaproth",
    "named_by": null,
    "appearance": "silvery-grey metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Uranium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "atomicMass": 237,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f4 6d1 7s2",
    "summary": "Neptunium is a chemical element with symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element.",
    "discovered_by": "Edwin McMillan",
    "named_by": null,
    "appearance": "silvery metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Neptunium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "atomicMass": 244,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f6 7s2",
    "summary": "Plutonium is a chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.",
    "discovered_by": "Glenn T. Seaborg",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Plutonium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 95,
    "symbol": "Am",
    "name": "Americium",
    "atomicMass": 243,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f7 7s2",
    "summary": "Americium is a radioactive chemical element with symbol Am and atomic number 95. It is a transuranic member of the actinide series.",
    "discovered_by": "Glenn T. Seaborg",
    "named_by": null,
    "appearance": "silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Americium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 96,
    "symbol": "Cm",
    "name": "Curium",
    "atomicMass": 247,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f7 6d1 7s2",
    "summary": "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie.",
    "discovered_by": "Glenn T. Seaborg",
    "named_by": null,
    "appearance": "silvery metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Curium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicMass": 247,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f9 7s2",
    "summary": "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.",
    "discovered_by": "Glenn T. Seaborg",
    "named_by": null,
    "appearance": "silvery",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Berkelium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 98,
    "symbol": "Cf",
    "name": "Californium",
    "atomicMass": 251,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f10 7s2",
    "summary": "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first synthesized in 1950 at the University of California, Berkeley.",
    "discovered_by": "Glenn T. Seaborg",
    "named_by": null,
    "appearance": "silvery",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Californium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicMass": 252,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f11 7s2",
    "summary": "Einsteinium is a synthetic element with symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide.",
    "discovered_by": "Albert Ghiorso",
    "named_by": null,
    "appearance": "silver-colored",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Einsteinium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "atomicMass": 257,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f12 7s2",
    "summary": "Fermium is a synthetic element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements.",
    "discovered_by": "Albert Ghiorso",
    "named_by": null,
    "appearance": "unknown, probably silvery white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Fermium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicMass": 258,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f13 7s2",
    "summary": "Mendelevium is a synthetic element with symbol Md (formerly Mv) and atomic number 101. A metallic radioactive transuranic element in the actinide series.",
    "discovered_by": "Albert Ghiorso",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Mendelevium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 102,
    "symbol": "No",
    "name": "Nobelium",
    "atomicMass": 259,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f14 7s2",
    "summary": "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.",
    "discovered_by": "Georgy Flerov",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Nobelium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicMass": 266,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 7s2 7p1",
    "summary": "Lawrencium is a synthetic chemical element with symbol Lr (formerly Lw) and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron.",
    "discovered_by": "Albert Ghiorso",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lawrencium",
    "color": "#f8bfff"
  },
  {
    "atomicNumber": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicMass": 267,
    "category": "transition-metal",
    "group": 4,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d2 7s2",
    "summary": "Rutherfordium is a chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element and radioactive.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Rutherfordium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "atomicMass": 268,
    "category": "transition-metal",
    "group": 5,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d3 7s2",
    "summary": "Dubnium is a chemical element with symbol Db and atomic number 105. It is named after the town of Dubna in Russia.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Dubnium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicMass": 269,
    "category": "transition-metal",
    "group": 6,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d4 7s2",
    "summary": "Seaborgium is a chemical element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg.",
    "discovered_by": "Lawrence Berkeley National Laboratory",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Seaborgium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicMass": 270,
    "category": "transition-metal",
    "group": 7,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d5 7s2",
    "summary": "Bohrium is a chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Bohrium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "atomicMass": 277,
    "category": "transition-metal",
    "group": 8,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d6 7s2",
    "summary": "Hassium is a chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Hassium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicMass": 278,
    "category": "transition-metal",
    "group": 9,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d7 7s2",
    "summary": "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is named after the Austrian physicist Lise Meitner.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Meitnerium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicMass": 281,
    "category": "transition-metal",
    "group": 10,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d9 7s1",
    "summary": "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is named after the city of Darmstadt, where it was discovered.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Darmstadtium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicMass": 282,
    "category": "transition-metal",
    "group": 11,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d10 7s1",
    "summary": "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is named after the physicist Wilhelm Röntgen.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Roentgenium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicMass": 285,
    "category": "transition-metal",
    "group": 12,
    "period": 7,
    "block": "d",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2",
    "summary": "Copernicium is a chemical element with symbol Cn and atomic number 112. It is named after the astronomer Nicolaus Copernicus.",
    "discovered_by": "GSI Helmholtz Centre for Heavy Ion Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Copernicium",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicMass": 286,
    "category": "post-transition-metal",
    "group": 13,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
    "summary": "Nihonium is a synthetic chemical element with symbol Nh and atomic number 113. It was named after the common Japanese name for Japan.",
    "discovered_by": "RIKEN",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Nihonium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicMass": 289,
    "category": "post-transition-metal",
    "group": 14,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
    "summary": "Flerovium is a synthetic chemical element with symbol Fl and atomic number 114. It is named after the Flerov Laboratory of Nuclear Reactions.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Flerovium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicMass": 290,
    "category": "post-transition-metal",
    "group": 15,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
    "summary": "Moscovium is a synthetic chemical element with symbol Mc and atomic number 115. It was named after the Moscow Oblast.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Moscovium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicMass": 293,
    "category": "post-transition-metal",
    "group": 16,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
    "summary": "Livermorium is a synthetic chemical element with symbol Lv and atomic number 116. It is named after the Lawrence Livermore National Laboratory.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Livermorium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicMass": 294,
    "category": "halogen",
    "group": 17,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
    "summary": "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is named after the state of Tennessee.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Tennessine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "atomicMass": 294,
    "category": "noble-gas",
    "group": 18,
    "period": 7,
    "block": "p",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
    "summary": "Oganesson is a radioactive, synthetic chemical element with symbol Og and atomic number 118. It is named after the physicist Yuri Oganessian.",
    "discovered_by": "Joint Institute for Nuclear Research",
    "named_by": null,
    "appearance": "unknown, probably gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Oganesson",
    "color": "#d0bfff"
  }
];
