// src/lib/chemical-elements-data.ts
export type ChemicalElement = {
  name: string;
  symbol: string;
  atomicNumber: number;
  atomicMass: number;
  category: string;
  group: number;
  period: number;
  block: string;
  electronConfiguration: string;
  summary: string;
  discovered_by: string;
  named_by: string | null;
  appearance: string | null;
  phase: 'Gas' | 'Liquid' | 'Solid';
  source: string; // URL to wikipedia
  color: string; // Hex color for category
};

export const CHEMICAL_ELEMENTS: ChemicalElement[] = [
  {
    "atomicNumber": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "atomicMass": 1.008,
    "category": "diatomic-nonmetal",
    "group": 1,
    "period": 1,
    "block": "s",
    "electronConfiguration": "1s1",
    "summary": "Hydrogen is the most abundant chemical element in the universe, constituting roughly 75% of all baryonic mass. It is a colorless, odorless, tasteless, non-toxic, and highly combustible diatomic gas with the molecular formula H₂.",
    "discovered_by": "Henry Cavendish",
    "named_by": "Antoine Lavoisier",
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Hydrogen",
    "color": "#a8ffc1"
  },
  {
    "atomicNumber": 2,
    "symbol": "He",
    "name": "Helium",
    "atomicMass": 4.0026,
    "category": "noble-gas",
    "group": 18,
    "period": 1,
    "block": "s",
    "electronConfiguration": "1s2",
    "summary": "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements.",
    "discovered_by": "Pierre Janssen & Norman Lockyer",
    "named_by": null,
    "appearance": "colorless gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Helium",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 3,
    "symbol": "Li",
    "name": "Lithium",
    "atomicMass": 6.94,
    "category": "alkali-metal",
    "group": 1,
    "period": 2,
    "block": "s",
    "electronConfiguration": "[He] 2s1",
    "summary": "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the least dense solid element. Like all alkali metals, lithium is highly reactive and flammable, and is stored in mineral oil.",
    "discovered_by": "Johan August Arfwedson",
    "named_by": null,
    "appearance": "silvery-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lithium",
    "color": "#ff6961"
  },
   {
    "atomicNumber": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "atomicMass": 9.01218315,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 2,
    "block": "s",
    "electronConfiguration": "[He] 2s2",
    "summary": "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.",
    "discovered_by": "Louis Nicolas Vauquelin",
    "named_by": null,
    "appearance": "white-gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Beryllium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 5,
    "symbol": "B",
    "name": "Boron",
    "atomicMass": 10.81,
    "category": "metalloid",
    "group": 13,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p1",
    "summary": "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar System and in the Earth's crust.",
    "discovered_by": "Joseph Louis Gay-Lussac",
    "named_by": null,
    "appearance": "black-brown",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Boron",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 6,
    "symbol": "C",
    "name": "Carbon",
    "atomicMass": 12.011,
    "category": "polyatomic-nonmetal",
    "group": 14,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p2",
    "summary": "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table. Carbon is the basis of all known life on Earth.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "black (graphite), transparent (diamond)",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Carbon",
    "color": "#b3b3b3"
  },
    {
    "atomicNumber": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "atomicMass": 14.007,
    "category": "diatomic-nonmetal",
    "group": 15,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p3",
    "summary": "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.",
    "discovered_by": "Daniel Rutherford",
    "named_by": "Jean-Antoine Chaptal",
    "appearance": "colorless gas, liquid or solid",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Nitrogen",
    "color": "#a8ffc1"
  },
  {
    "atomicNumber": 8,
    "symbol": "O",
    "name": "Oxygen",
    "atomicMass": 15.999,
    "category": "diatomic-nonmetal",
    "group": 16,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p4",
    "summary": "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.",
    "discovered_by": "Carl Wilhelm Scheele & Joseph Priestley",
    "named_by": "Antoine Lavoisier",
    "appearance": "colorless gas, pale blue liquid",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Oxygen",
    "color": "#a8ffc1"
  },
    {
    "atomicNumber": 9,
    "symbol": "F",
    "name": "Fluorine",
    "atomicMass": 18.9984031636,
    "category": "halogen",
    "group": 17,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p5",
    "summary": "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.",
    "discovered_by": "Henri Moissan",
    "named_by": null,
    "appearance": "pale yellow gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Fluorine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 10,
    "symbol": "Ne",
    "name": "Neon",
    "atomicMass": 20.17976,
    "category": "noble-gas",
    "group": 18,
    "period": 2,
    "block": "p",
    "electronConfiguration": "[He] 2s2 2p6",
    "summary": "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas. Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.",
    "discovered_by": "Morris Travers, William Ramsay",
    "named_by": null,
    "appearance": "colorless gas exhibiting an orange-red glow when placed in an electric field",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Neon",
    "color": "#d0bfff"
  },
    {
    "atomicNumber": 11,
    "symbol": "Na",
    "name": "Sodium",
    "atomicMass": 22.989769282,
    "category": "alkali-metal",
    "group": 1,
    "period": 3,
    "block": "s",
    "electronConfiguration": "[Ne] 3s1",
    "summary": "Sodium is a chemical element with symbol Na (from Neo-Latin natrium) and atomic number 11. It is a soft, silvery-white, highly reactive metal.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "silvery white metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Sodium",
    "color": "#ff6961"
  },
    {
    "atomicNumber": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicMass": 24.305,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 3,
    "block": "s",
    "electronConfiguration": "[Ne] 3s2",
    "summary": "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (Group 2, or alkaline earth metals) of the periodic table: all Group 2 elements have the same electron configuration in the outer electron shell and a similar crystal structure.",
    "discovered_by": "Joseph Black",
    "named_by": null,
    "appearance": "shiny grey solid",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Magnesium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 13,
    "symbol": "Al",
    "name": "Aluminium",
    "atomicMass": 26.98153857,
    "category": "post-transition-metal",
    "group": 13,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p1",
    "summary": "Aluminium (or aluminum in American and Canadian English) is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, non-magnetic and ductile metal in the boron group.",
    "discovered_by": "Hans Christian Ørsted",
    "named_by": null,
    "appearance": "silvery-gray metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Aluminium",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 14,
    "symbol": "Si",
    "name": "Silicon",
    "atomicMass": 28.085,
    "category": "metalloid",
    "group": 14,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p2",
    "summary": "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard, brittle crystalline solid with a blue-grey metallic lustre, and is a tetravalent metalloid and semiconductor.",
    "discovered_by": "Jöns Jacob Berzelius",
    "named_by": null,
    "appearance": "crystalline, reflective with bluish-tinged faces",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Silicon",
    "color": "#fdfd96"
  },
  {
    "atomicNumber": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "atomicMass": 30.9737619985,
    "category": "polyatomic-nonmetal",
    "group": 15,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p3",
    "summary": "Phosphorus is a chemical element with symbol P and atomic number 15. Elemental phosphorus exists in two major forms, white phosphorus and red phosphorus, but because it is highly reactive, phosphorus is never found as a free element on Earth.",
    "discovered_by": "Hennig Brand",
    "named_by": null,
    "appearance": "colorless, waxy white, yellow, scarlet, red, violet, black",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Phosphorus",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 16,
    "symbol": "S",
    "name": "Sulfur",
    "atomicMass": 32.06,
    "category": "polyatomic-nonmetal",
    "group": 16,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p4",
    "summary": "Sulfur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S₈.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lemon yellow sintered microcrystals",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Sulfur",
    "color": "#b3b3b3"
  },
  {
    "atomicNumber": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicMass": 35.45,
    "category": "halogen",
    "group": 17,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p5",
    "summary": "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.",
    "discovered_by": "Carl Wilhelm Scheele",
    "named_by": null,
    "appearance": "pale yellow-green gas",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Chlorine",
    "color": "#ffff99"
  },
  {
    "atomicNumber": 18,
    "symbol": "Ar",
    "name": "Argon",
    "atomicMass": 39.9481,
    "category": "noble-gas",
    "group": 18,
    "period": 3,
    "block": "p",
    "electronConfiguration": "[Ne] 3s2 3p6",
    "summary": "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934% (9340 ppmv).",
    "discovered_by": "Lord Rayleigh, William Ramsay",
    "named_by": null,
    "appearance": "colorless gas exhibiting a lilac/violet glow when placed in an electric field",
    "phase": "Gas",
    "source": "https://en.wikipedia.org/wiki/Argon",
    "color": "#d0bfff"
  },
  {
    "atomicNumber": 19,
    "symbol": "K",
    "name": "Potassium",
    "atomicMass": 39.09831,
    "category": "alkali-metal",
    "group": 1,
    "period": 4,
    "block": "s",
    "electronConfiguration": "[Ar] 4s1",
    "summary": "Potassium is a chemical element with symbol K (from Neo-Latin kalium) and atomic number 19. It is a silvery-white metal that is soft enough to be cut with a knife with little force.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "silvery-white",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Potassium",
    "color": "#ff6961"
  },
  {
    "atomicNumber": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "atomicMass": 40.0784,
    "category": "alkaline-earth-metal",
    "group": 2,
    "period": 4,
    "block": "s",
    "electronConfiguration": "[Ar] 4s2",
    "summary": "Calcium is a chemical element with symbol Ca and atomic number 20. As an alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.",
    "discovered_by": "Humphry Davy",
    "named_by": null,
    "appearance": "dull gray, silver",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Calcium",
    "color": "#ffb347"
  },
  {
    "atomicNumber": 26,
    "symbol": "Fe",
    "name": "Iron",
    "atomicMass": 55.845,
    "category": "transition-metal",
    "group": 8,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d6 4s2",
    "summary": "Iron is a chemical element with symbol Fe and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table. It is by mass the most common element on Earth, forming much of Earth's outer and inner core. It is the fourth most common element in the Earth's crust.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lustrous metallic with a grayish tinge",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Iron",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 29,
    "symbol": "Cu",
    "name": "Copper",
    "atomicMass": 63.546,
    "category": "transition-metal",
    "group": 11,
    "period": 4,
    "block": "d",
    "electronConfiguration": "[Ar] 3d10 4s1",
    "summary": "Copper is a chemical element with symbol Cu and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "red-orange metallic luster",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Copper",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 47,
    "symbol": "Ag",
    "name": "Silver",
    "atomicMass": 107.8682,
    "category": "transition-metal",
    "group": 11,
    "period": 5,
    "block": "d",
    "electronConfiguration": "[Kr] 4d10 5s1",
    "summary": "Silver is a chemical element with symbol Ag and atomic number 47. A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "lustrous white metal",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Silver",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 79,
    "symbol": "Au",
    "name": "Gold",
    "atomicMass": 196.96657,
    "category": "transition-metal",
    "group": 11,
    "period": 6,
    "block": "d",
    "electronConfiguration": "[Xe] 4f14 5d10 6s1",
    "summary": "Gold is a chemical element with symbol Au and atomic number 79, making it one of the higher atomic number elements that occur naturally. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "metallic yellow",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Gold",
    "color": "#ffc1c1"
  },
  {
    "atomicNumber": 82,
    "symbol": "Pb",
    "name": "Lead",
    "atomicMass": 207.2,
    "category": "post-transition-metal",
    "group": 14,
    "period": 6,
    "block": "p",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
    "summary": "Lead is a chemical element with symbol Pb and atomic number 82. It is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point. When freshly cut, lead is silvery with a hint of blue; it tarnishes to a dull gray color when exposed to air.",
    "discovered_by": "Ancient civilizations",
    "named_by": null,
    "appearance": "metallic gray",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Lead",
    "color": "#d1d1e0"
  },
  {
    "atomicNumber": 92,
    "symbol": "U",
    "name": "Uranium",
    "atomicMass": 238.02891,
    "category": "actinide",
    "group": 3,
    "period": 7,
    "block": "f",
    "electronConfiguration": "[Rn] 5f3 6d1 7s2",
    "summary": "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons. Uranium is weakly radioactive because all isotopes of uranium are unstable.",
    "discovered_by": "Martin Heinrich Klaproth",
    "named_by": null,
    "appearance": "silvery-grey metallic",
    "phase": "Solid",
    "source": "https://en.wikipedia.org/wiki/Uranium",
    "color": "#f8bfff"
  }
];
