
export const COUNTRIES_DATA = [
  { country: "United States", cities: ["New York", "Los Angeles", "Chicago", "Miami", "San Francisco"] },
  { country: "Canada", cities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"] },
  { country: "Brazil", cities: ["Rio de Janeiro", "São Paulo", "Salvador", "Fortaleza", "Brasília"] },
  { country: "Argentina", cities: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "Ushuaia"] },
  { country: "United Kingdom", cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Bristol"] },
  { country: "France", cities: ["Paris", "Nice", "Marseille", "Lyon", "Bordeaux"] },
  { country: "Germany", cities: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"] },
  { country: "Spain", cities: ["Barcelona", "Madrid", "Seville", "Valencia", "Ibiza"] },
  { country: "Italy", cities: ["Rome", "Florence", "Venice", "Milan", "Amalfi Coast"] },
  { country: "Japan", cities: ["Tokyo", "Kyoto", "Osaka", "Sapporo", "Fukuoka"] },
  { country: "South Korea", cities: ["Seoul", "Busan", "Jeju Island", "Incheon", "Gyeongju"] },
  { country: "China", cities: ["Beijing", "Shanghai", "Hong Kong", "Xi'an", "Chengdu"] },
  { country: "India", cities: ["Delhi", "Mumbai", "Jaipur", "Agra", "Goa"] },
  { country: "Australia", cities: ["Sydney", "Melbourne", "Cairns", "Perth", "Adelaide"] },
  { country: "New Zealand", cities: ["Auckland", "Queenstown", "Wellington", "Christchurch", "Rotorua"] },
  { country: "Egypt", cities: ["Cairo", "Luxor", "Aswan", "Giza", "Alexandria"] },
  { country: "South Africa", cities: ["Cape Town", "Johannesburg", "Durban", "Kruger National Park", "Stellenbosch"] },
  { country: "Kenya", cities: ["Nairobi", "Mombasa", "Maasai Mara", "Lamu", "Kisumu"] },
  { country: "Thailand", cities: ["Bangkok", "Chiang Mai", "Phuket", "Krabi", "Pattaya"] },
  { country: "Indonesia", cities: ["Bali", "Jakarta", "Yogyakarta", "Lombok", "Komodo Island"] },
  { country: "Vietnam", cities: ["Hanoi", "Ho Chi Minh City", "Ha Long Bay", "Hoi An", "Da Nang"] },
  { country: "Mexico", cities: ["Mexico City", "Cancun", "Tulum", "Oaxaca", "Guadalajara"] },
  { country: "Peru", cities: ["Lima", "Cusco", "Machu Picchu", "Arequipa", "Iquitos"] },
  { country: "Greece", cities: ["Athens", "Santorini", "Mykonos", "Crete", "Rhodes"] },
  { country: "Turkey", cities: ["Istanbul", "Cappadocia", "Antalya", "Bodrum", "Pamukkale"] },
];
