
export const COUNTRIES_DATA = [
  // Americas
  { country: "United States", cities: ["New York", "Los Angeles", "Chicago", "Miami", "San Francisco"] },
  { country: "Canada", cities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Quebec City"] },
  { country: "Brazil", cities: ["Rio de Janeiro", "São Paulo", "Salvador", "Fortaleza", "Manaus"] },
  { country: "Argentina", cities: ["Buenos Aires", "Cordoba", "Mendoza", "Bariloche", "Ushuaia"] },
  { country: "Mexico", cities: ["Mexico City", "Cancun", "Tulum", "Oaxaca", "Guadalajara"] },
  { country: "Peru", cities: ["Lima", "Cusco", "Arequipa", "Machu Picchu", "Iquitos"] },
  { country: "Colombia", cities: ["Bogotá", "Medellín", "Cartagena", "Cali", "Santa Marta"] },
  { country: "Chile", cities: ["Santiago", "Valparaíso", "San Pedro de Atacama", "Puerto Varas", "Easter Island"] },
  { country: "Costa Rica", cities: ["San José", "La Fortuna", "Monteverde", "Tamarindo", "Puerto Viejo"] },
  { country: "Cuba", cities: ["Havana", "Trinidad", "Varadero", "Viñales", "Santiago de Cuba"] },
  
  // Europe
  { country: "United Kingdom", cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Bath"] },
  { country: "France", cities: ["Paris", "Nice", "Marseille", "Lyon", "Bordeaux"] },
  { country: "Germany", cities: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"] },
  { country: "Spain", cities: ["Barcelona", "Madrid", "Seville", "Valencia", "Ibiza"] },
  { country: "Italy", cities: ["Rome", "Florence", "Venice", "Milan", "Amalfi Coast"] },
  { country: "Greece", cities: ["Athens", "Santorini", "Mykonos", "Crete", "Rhodes"] },
  { country: "Portugal", cities: ["Lisbon", "Porto", "Algarve", "Sintra", "Madeira"] },
  { country: "Netherlands", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Giethoorn"] },
  { country: "Ireland", cities: ["Dublin", "Galway", "Cork", "Killarney", "Limerick"] },
  { country: "Switzerland", cities: ["Zurich", "Geneva", "Interlaken", "Lucerne", "Zermatt"] },
  { country: "Austria", cities: ["Vienna", "Salzburg", "Innsbruck", "Hallstatt", "Graz"] },
  { country: "Belgium", cities: ["Brussels", "Bruges", "Ghent", "Antwerp", "Dinant"] },
  { country: "Sweden", cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Kiruna"] },
  { country: "Norway", cities: ["Oslo", "Bergen", "Tromsø", "Stavanger", "Lofoten Islands"] },
  { country: "Denmark", cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Skagen"] },
  { country: "Finland", cities: ["Helsinki", "Rovaniemi", "Tampere", "Turku", "Oulu"] },
  { country: "Iceland", cities: ["Reykjavik", "Akureyri", "Vík", "Húsavík", "Selfoss"] },
  { country: "Croatia", cities: ["Dubrovnik", "Split", "Hvar", "Zagreb", "Plitvice Lakes"] },
  { country: "Czech Republic", cities: ["Prague", "Český Krumlov", "Brno", "Karlovy Vary", "Pilsen"] },
  { country: "Hungary", cities: ["Budapest", "Debrecen", "Szeged", "Pécs", "Győr"] },
  { country: "Poland", cities: ["Krakow", "Warsaw", "Gdańsk", "Wrocław", "Zakopane"] },
  
  // Asia
  { country: "Japan", cities: ["Tokyo", "Kyoto", "Osaka", "Sapporo", "Okinawa"] },
  { country: "South Korea", cities: ["Seoul", "Busan", "Jeju Island", "Incheon", "Gyeongju"] },
  { country: "China", cities: ["Beijing", "Shanghai", "Hong Kong", "Xi'an", "Guilin"] },
  { country: "India", cities: ["Delhi", "Mumbai", "Jaipur", "Agra", "Varanasi"] },
  { country: "Thailand", cities: ["Bangkok", "Chiang Mai", "Phuket", "Krabi", "Koh Samui"] },
  { country: "Indonesia", cities: ["Bali", "Jakarta", "Yogyakarta", "Lombok", "Komodo Island"] },
  { country: "Vietnam", cities: ["Hanoi", "Ho Chi Minh City", "Ha Long Bay", "Hoi An", "Da Nang"] },
  { country: "Malaysia", cities: ["Kuala Lumpur", "Penang", "Langkawi", "Malacca", "Kota Kinabalu"] },
  { country: "Philippines", cities: ["Manila", "Cebu", "Palawan", "Boracay", "Siargao"] },
  { country: "Singapore", cities: ["Singapore"] },
  { country: "Turkey", cities: ["Istanbul", "Cappadocia", "Antalya", "Bodrum", "Pamukkale"] },
  { country: "United Arab Emirates", cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ras Al Khaimah", "Fujairah"] },
  { country: "Israel", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat", "Dead Sea"] },
  { country: "Jordan", cities: ["Amman", "Petra", "Wadi Rum", "Aqaba", "Jerash"] },
  { country: "Nepal", cities: ["Kathmandu", "Pokhara", "Chitwan National Park", "Lumbini", "Nagarkot"] },
  
  // Africa
  { country: "Egypt", cities: ["Cairo", "Luxor", "Aswan", "Giza", "Alexandria"] },
  { country: "South Africa", cities: ["Cape Town", "Johannesburg", "Durban", "Kruger National Park", "Stellenbosch"] },
  { country: "Kenya", cities: ["Nairobi", "Mombasa", "Maasai Mara", "Lamu", "Nakuru"] },
  { country: "Morocco", cities: ["Marrakech", "Fes", "Casablanca", "Chefchaouen", "Rabat"] },
  { country: "Tanzania", cities: ["Dar es Salaam", "Zanzibar", "Arusha", "Serengeti", "Mwanza"] },
  { country: "Nigeria", cities: ["Lagos", "Abuja", "Kano", "Ibadan", "Calabar"] },
  { country: "Ghana", cities: ["Accra", "Kumasi", "Cape Coast", "Takoradi", "Tamale"] },
  { country: "Ethiopia", cities: ["Addis Ababa", "Lalibela", "Gondar", "Axum", "Bahir Dar"] },

  // Oceania
  { country: "Australia", cities: ["Sydney", "Melbourne", "Cairns", "Perth", "Uluru"] },
  { country: "New Zealand", cities: ["Auckland", "Queenstown", "Wellington", "Christchurch", "Rotorua"] },
  { country: "Fiji", cities: ["Nadi", "Suva", "Mamanuca Islands", "Yasawa Islands", "Taveuni"] },
  { country: "French Polynesia", cities: ["Bora Bora", "Tahiti", "Moorea", "Papeete", "Rangiroa"] }
];
