export const COUNTRY_CODES = [
  { name: 'Afghanistan', code: 'AF', lang: 'fa' },
  { name: 'Åland Islands', code: 'AX', lang: 'sv' },
  { name: 'Albania', code: 'AL', lang: 'sq' },
  { name: 'Algeria', code: 'DZ', lang: 'ar' },
  { name: 'American Samoa', code: 'AS', lang: 'en' },
  { name: 'Andorra', code: 'AD', lang: 'ca' },
  { name: 'Angola', code: 'AO', lang: 'pt' },
  { name: 'Anguilla', code: 'AI', lang: 'en' },
  { name: 'Antarctica', code: 'AQ', lang: 'en' },
  { name: 'Antigua and Barbuda', code: 'AG', lang: 'en' },
  { name: 'Argentina', code: 'AR', lang: 'es' },
  { name: 'Armenia', code: 'AM', lang: 'hy' },
  { name: 'Aruba', code: 'AW', lang: 'nl' },
  { name: 'Australia', code: 'AU', lang: 'en' },
  { name: 'Austria', code: 'AT', lang: 'de' },
  { name: 'Azerbaijan', code: 'AZ', lang: 'az' },
  { name: 'Bahamas', code: 'BS', lang: 'en' },
  { name: 'Bahrain', code: 'BH', lang: 'ar' },
  { name: 'Bangladesh', code: 'BD', lang: 'bn' },
  { name: 'Barbados', code: 'BB', lang: 'en' },
  { name: 'Belarus', code: 'BY', lang: 'be' },
  { name: 'Belgium', code: 'BE', lang: 'nl' },
  { name: 'Belize', code: 'BZ', lang: 'en' },
  { name: 'Benin', code: 'BJ', lang: 'fr' },
  { name: 'Bermuda', code: 'BM', lang: 'en' },
  { name: 'Bhutan', code: 'BT', lang: 'dz' },
  { name: 'Bolivia', code: 'BO', lang: 'es' },
  { name: 'Bosnia and Herzegovina', code: 'BA', lang: 'bs' },
  { name: 'Botswana', code: 'BW', lang: 'en' },
  { name: 'Bouvet Island', code: 'BV', lang: 'no' },
  { name: 'Brazil', code: 'BR', lang: 'pt' },
  { name: 'British Indian Ocean Territory', code: 'IO', lang: 'en' },
  { name: 'Brunei Darussalam', code: 'BN', lang: 'ms' },
  { name: 'Bulgaria', code: 'BG', lang: 'bg' },
  { name: 'Burkina Faso', code: 'BF', lang: 'fr' },
  { name: 'Burundi', code: 'BI', lang: 'fr' },
  { name: 'Cambodia', code: 'KH', lang: 'km' },
  { name: 'Cameroon', code: 'CM', lang: 'en' },
  { name: 'Canada', code: 'CA', lang: 'en' },
  { name: 'Cape Verde', code: 'CV', lang: 'pt' },
  { name: 'Cayman Islands', code: 'KY', lang: 'en' },
  { name: 'Central African Republic', code: 'CF', lang: 'fr' },
  { name: 'Chad', code: 'TD', lang: 'fr' },
  { name: 'Chile', code: 'CL', lang: 'es' },
  { name: 'China', code: 'CN', lang: 'zh' },
  { name: 'Christmas Island', code: 'CX', lang: 'en' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', lang: 'en' },
  { name: 'Colombia', code: 'CO', lang: 'es' },
  { name: 'Comoros', code: 'KM', lang: 'ar' },
  { name: 'Congo', code: 'CG', lang: 'fr' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD', lang: 'fr' },
  { name: 'Cook Islands', code: 'CK', lang: 'en' },
  { name: 'Costa Rica', code: 'CR', lang: 'es' },
  { name: "Côte D'Ivoire", code: 'CI', lang: 'fr' },
  { name: 'Croatia', code: 'HR', lang: 'hr' },
  { name: 'Cuba', code: 'CU', lang: 'es' },
  { name: 'Cyprus', code: 'CY', lang: 'el' },
  { name: 'Czech Republic', code: 'CZ', lang: 'cs' },
  { name: 'Denmark', code: 'DK', lang: 'da' },
  { name: 'Djibouti', code: 'DJ', lang: 'fr' },
  { name: 'Dominica', code: 'DM', lang: 'en' },
  { name: 'Dominican Republic', code: 'DO', lang: 'es' },
  { name: 'Ecuador', code: 'EC', lang: 'es' },
  { name: 'Egypt', code: 'EG', lang: 'ar' },
  { name: 'El Salvador', code: 'SV', lang: 'es' },
  { name: 'Equatorial Guinea', code: 'GQ', lang: 'es' },
  { name: 'Eritrea', code: 'ER', lang: 'ti' },
  { name: 'Estonia', code: 'EE', lang: 'et' },
  { name: 'Ethiopia', code: 'ET', lang: 'am' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', lang: 'en' },
  { name: 'Faroe Islands', code: 'FO', lang: 'fo' },
  { name: 'Fiji', code: 'FJ', lang: 'en' },
  { name: 'Finland', code: 'FI', lang: 'fi' },
  { name: 'France', code: 'FR', lang: 'fr' },
  { name: 'French Guiana', code: 'GF', lang: 'fr' },
  { name: 'French Polynesia', code: 'PF', lang: 'fr' },
  { name: 'French Southern Territories', code: 'TF', lang: 'fr' },
  { name: 'Gabon', code: 'GA', lang: 'fr' },
  { name: 'Gambia', code: 'GM', lang: 'en' },
  { name: 'Georgia', code: 'GE', lang: 'ka' },
  { name: 'Germany', code: 'DE', lang: 'de' },
  { name: 'Ghana', code: 'GH', lang: 'en' },
  { name: 'Gibraltar', code: 'GI', lang: 'en' },
  { name: 'Greece', code: 'GR', lang: 'el' },
  { name: 'Greenland', code: 'GL', lang: 'kl' },
  { name: 'Grenada', code: 'GD', lang: 'en' },
  { name: 'Guadeloupe', code: 'GP', lang: 'fr' },
  { name: 'Guam', code: 'GU', lang: 'en' },
  { name: 'Guatemala', code: 'GT', lang: 'es' },
  { name: 'Guernsey', code: 'GG', lang: 'en' },
  { name: 'Guinea', code: 'GN', lang: 'fr' },
  { name: 'Guinea-Bissau', code: 'GW', lang: 'pt' },
  { name: 'Guyana', code: 'GY', lang: 'en' },
  { name: 'Haiti', code: 'HT', lang: 'fr' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM', lang: 'en' },
  { name: 'Holy See (Vatican City State)', code: 'VA', lang: 'it' },
  { name: 'Honduras', code: 'HN', lang: 'es' },
  { name: 'Hong Kong', code: 'HK', lang: 'zh' },
  { name: 'Hungary', code: 'HU', lang: 'hu' },
  { name: 'Iceland', code: 'IS', lang: 'is' },
  { name: 'India', code: 'IN', lang: 'hi' },
  { name: 'Indonesia', code: 'ID', lang: 'id' },
  { name: 'Iran, Islamic Republic Of', code: 'IR', lang: 'fa' },
  { name: 'Iraq', code: 'IQ', lang: 'ar' },
  { name: 'Ireland', code: 'IE', lang: 'en' },
  { name: 'Isle of Man', code: 'IM', lang: 'en' },
  { name: 'Israel', code: 'IL', lang: 'he' },
  { name: 'Italy', code: 'IT', lang: 'it' },
  { name: 'Jamaica', code: 'JM', lang: 'en' },
  { name: 'Japan', code: 'JP', lang: 'ja' },
  { name: 'Jersey', code: 'JE', lang: 'en' },
  { name: 'Jordan', code: 'JO', lang: 'ar' },
  { name: 'Kazakhstan', code: 'KZ', lang: 'kk' },
  { name: 'Kenya', code: 'KE', lang: 'en' },
  { name: 'Kiribati', code: 'KI', lang: 'en' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP', lang: 'ko' },
  { name: 'Korea, Republic of', code: 'KR', lang: 'ko' },
  { name: 'Kuwait', code: 'KW', lang: 'ar' },
  { name: 'Kyrgyzstan', code: 'KG', lang: 'ky' },
  { name: "Lao People'S Democratic Republic", code: 'LA', lang: 'lo' },
  { name: 'Latvia', code: 'LV', lang: 'lv' },
  { name: 'Lebanon', code: 'LB', lang: 'ar' },
  { name: 'Lesotho', code: 'LS', lang: 'en' },
  { name: 'Liberia', code: 'LR', lang: 'en' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY', lang: 'ar' },
  { name: 'Liechtenstein', code: 'LI', lang: 'de' },
  { name: 'Lithuania', code: 'LT', lang: 'lt' },
  { name: 'Luxembourg', code: 'LU', lang: 'fr' },
  { name: 'Macao', code: 'MO', lang: 'zh' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK', lang: 'mk' },
  { name: 'Madagascar', code: 'MG', lang: 'fr' },
  { name: 'Malawi', code: 'MW', lang: 'en' },
  { name: 'Malaysia', code: 'MY', lang: 'ms' },
  { name: 'Maldives', code: 'MV', lang: 'dv' },
  { name: 'Mali', code: 'ML', lang: 'fr' },
  { name: 'Malta', code: 'MT', lang: 'mt' },
  { name: 'Marshall Islands', code: 'MH', lang: 'en' },
  { name: 'Martinique', code: 'MQ', lang: 'fr' },
  { name: 'Mauritania', code: 'MR', lang: 'ar' },
  { name: 'Mauritius', code: 'MU', lang: 'en' },
  { name: 'Mayotte', code: 'YT', lang: 'fr' },
  { name: 'Mexico', code: 'MX', lang: 'es' },
  { name: 'Micronesia, Federated States of', code: 'FM', lang: 'en' },
  { name: 'Moldova, Republic of', code: 'MD', lang: 'ro' },
  { name: 'Monaco', code: 'MC', lang: 'fr' },
  { name: 'Mongolia', code: 'MN', lang: 'mn' },
  { name: 'Montserrat', code: 'MS', lang: 'en' },
  { name: 'Morocco', code: 'MA', lang: 'ar' },
  { name: 'Mozambique', code: 'MZ', lang: 'pt' },
  { name: 'Myanmar', code: 'MM', lang: 'my' },
  { name: 'Namibia', code: 'NA', lang: 'en' },
  { name: 'Nauru', code: 'NR', lang: 'en' },
  { name: 'Nepal', code: 'NP', lang: 'ne' },
  { name: 'Netherlands', code: 'NL', lang: 'nl' },
  { name: 'Netherlands Antilles', code: 'AN', lang: 'nl' },
  { name: 'New Caledonia', code: 'NC', lang: 'fr' },
  { name: 'New Zealand', code: 'NZ', lang: 'en' },
  { name: 'Nicaragua', code: 'NI', lang: 'es' },
  { name: 'Niger', code: 'NE', lang: 'fr' },
  { name: 'Nigeria', code: 'NG', lang: 'en' },
  { name: 'Niue', code: 'NU', lang: 'en' },
  { name: 'Norfolk Island', code: 'NF', lang: 'en' },
  { name: 'Northern Mariana Islands', code: 'MP', lang: 'en' },
  { name: 'Norway', code: 'NO', lang: 'no' },
  { name: 'Oman', code: 'OM', lang: 'ar' },
  { name: 'Pakistan', code: 'PK', lang: 'ur' },
  { name: 'Palau', code: 'PW', lang: 'en' },
  { name: 'Palestinian Territory, Occupied', code: 'PS', lang: 'ar' },
  { name: 'Panama', code: 'PA', lang: 'es' },
  { name: 'Papua New Guinea', code: 'PG', lang: 'en' },
  { name: 'Paraguay', code: 'PY', lang: 'es' },
  { name: 'Peru', code: 'PE', lang: 'es' },
  { name: 'Philippines', code: 'PH', lang: 'en' },
  { name: 'Pitcairn', code: 'PN', lang: 'en' },
  { name: 'Poland', code: 'PL', lang: 'pl' },
  { name: 'Portugal', code: 'PT', lang: 'pt' },
  { name: 'Puerto Rico', code: 'PR', lang: 'es' },
  { name: 'Qatar', code: 'QA', lang: 'ar' },
  { name: 'Reunion', code: 'RE', lang: 'fr' },
  { name: 'Romania', code: 'RO', lang: 'ro' },
  { name: 'Russian Federation', code: 'RU', lang: 'ru' },
  { name: 'Rwanda', code: 'RW', lang: 'rw' },
  { name: 'Saint Helena', code: 'SH', lang: 'en' },
  { name: 'Saint Kitts and Nevis', code: 'KN', lang: 'en' },
  { name: 'Saint Lucia', code: 'LC', lang: 'en' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', lang: 'fr' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', lang: 'en' },
  { name: 'Samoa', code: 'WS', lang: 'sm' },
  { name: 'San Marino', code: 'SM', lang: 'it' },
  { name: 'Sao Tome and Principe', code: 'ST', lang: 'pt' },
  { name: 'Saudi Arabia', code: 'SA', lang: 'ar' },
  { name: 'Senegal', code: 'SN', lang: 'fr' },
  { name: 'Serbia and Montenegro', code: 'CS', lang: 'sr' },
  { name: 'Seychelles', code: 'SC', lang: 'fr' },
  { name: 'Sierra Leone', code: 'SL', lang: 'en' },
  { name: 'Singapore', code: 'SG', lang: 'en' },
  { name: 'Slovakia', code: 'SK', lang: 'sk' },
  { name: 'Slovenia', code: 'SI', lang: 'sl' },
  { name: 'Solomon Islands', code: 'SB', lang: 'en' },
  { name: 'Somalia', code: 'SO', lang: 'so' },
  { name: 'South Africa', code: 'ZA', lang: 'en' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS', lang: 'en' },
  { name: 'Spain', code: 'ES', lang: 'es' },
  { name: 'Sri Lanka', code: 'LK', lang: 'si' },
  { name: 'Sudan', code: 'SD', lang: 'ar' },
  { name: 'Suriname', code: 'SR', lang: 'nl' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', lang: 'no' },
  { name: 'Swaziland', code: 'SZ', lang: 'en' },
  { name: 'Sweden', code: 'SE', lang: 'sv' },
  { name: 'Switzerland', code: 'CH', lang: 'de' },
  { name: 'Syrian Arab Republic', code: 'SY', lang: 'ar' },
  { name: 'Taiwan', code: 'TW', lang: 'zh' },
  { name: 'Tajikistan', code: 'TJ', lang: 'tg' },
  { name: 'Tanzania, United Republic of', code: 'TZ', lang: 'sw' },
  { name: 'Thailand', code: 'TH', lang: 'th' },
  { name: 'Timor-Leste', code: 'TL', lang: 'pt' },
  { name: 'Togo', code: 'TG', lang: 'fr' },
  { name: 'Tokelau', code: 'TK', lang: 'en' },
  { name: 'Tonga', code: 'TO', lang: 'to' },
  { name: 'Trinidad and Tobago', code: 'TT', lang: 'en' },
  { name: 'Tunisia', code: 'TN', lang: 'ar' },
  { name: 'Turkey', code: 'TR', lang: 'tr' },
  { name: 'Turkmenistan', code: 'TM', lang: 'tk' },
  { name: 'Turks and Caicos Islands', code: 'TC', lang: 'en' },
  { name: 'Tuvalu', code: 'TV', lang: 'en' },
  { name: 'Uganda', code: 'UG', lang: 'en' },
  { name: 'Ukraine', code: 'UA', lang: 'uk' },
  { name: 'United Arab Emirates', code: 'AE', lang: 'ar' },
  { name: 'United Kingdom', code: 'GB', lang: 'en' },
  { name: 'United States', code: 'US', lang: 'en' },
  { name: 'United States Minor Outlying Islands', code: 'UM', lang: 'en' },
  { name: 'Uruguay', code: 'UY', lang: 'es' },
  { name: 'Uzbekistan', code: 'UZ', lang: 'uz' },
  { name: 'Vanuatu', code: 'VU', lang: 'bi' },
  { name: 'Venezuela', code: 'VE', lang: 'es' },
  { name: 'Viet Nam', code: 'VN', lang: 'vi' },
  { name: 'Virgin Islands, British', code: 'VG', lang: 'en' },
  { name: 'Virgin Islands, U.S.', code: 'VI', lang: 'en' },
  { name: 'Wallis and Futuna', code: 'WF', lang: 'fr' },
  { name: 'Western Sahara', code: 'EH', lang: 'es' },
  { name: 'Yemen', code: 'YE', lang: 'ar' },
  { name: 'Zambia', code: 'ZM', lang: 'en' },
  { name: 'Zimbabwe', code: 'ZW', lang: 'en' },
].sort((a, b) => a.name.localeCompare(b.name));
