
export const GIFTS_LIST = [
    { "for": "Wife", "item": "Personalized jewelry with initials", "tags": ["anniversary", "valentine", "birthday"] },
    { "for": "Wife", "item": "Spa day or massage voucher", "tags": ["birthday", "thank_you", "anniversary"] },
    { "for": "Wife", "item": "Scented candle set", "tags": ["romantic", "christmas", "home"] },
    { "for": "Wife", "item": "Romantic dinner date", "tags": ["anniversary", "valentine"] },
    { "for": "Wife", "item": "Luxury skincare set", "tags": ["birthday", "christmas", "beauty"] },
    { "for": "Wife", "item": "Customized photo book", "tags": ["anniversary", "memory", "birthday"] },
    { "for": "Wife", "item": "Perfume gift box", "tags": ["birthday", "valentine", "luxury"] },
    { "for": "Wife", "item": "Weekend getaway trip", "tags": ["anniversary", "holiday", "romantic"] },
    { "for": "Wife", "item": "Stylish handbag", "tags": ["birthday", "fashion", "christmas"] },
    { "for": "Wife", "item": "A handwritten love letter", "tags": ["valentine", "anniversary"] },
    { "for": "Wife", "item": "Matching couple bracelet", "tags": ["anniversary", "valentine"] },
    { "for": "Wife", "item": "Luxury pajamas set", "tags": ["birthday", "comfort"] },
    { "for": "Wife", "item": "Silk scarf", "tags": ["fashion", "christmas", "birthday"] },
    { "for": "Wife", "item": "Customized name necklace", "tags": ["birthday", "anniversary", "personalized"] },
    { "for": "Wife", "item": "A book from her favorite author", "tags": ["birthday", "christmas", "reading"] },
    { "for": "Wife", "item": "Subscription to beauty box", "tags": ["birthday", "monthly", "surprise"] },
    { "for": "Wife", "item": "Cozy blanket set", "tags": ["home", "winter", "comfort"] },
    { "for": "Wife", "item": "A bouquet of roses", "tags": ["valentine", "anniversary", "random"] },
    { "for": "Wife", "item": "Jewelry box organizer", "tags": ["birthday", "practical", "christmas"] },
    { "for": "Wife", "item": "Cooking class for couples", "tags": ["anniversary", "activity", "fun"] },
    { "for": "Wife", "item": "Framed custom portrait", "tags": ["anniversary", "home", "art"] },
    { "for": "Wife", "item": "Personalized phone case", "tags": ["birthday", "casual"] },
    { "for": "Wife", "item": "Favorite dessert box", "tags": ["birthday", "valentine", "random"] },
    { "for": "Wife", "item": "Fitness membership or yoga mat", "tags": ["health", "birthday", "new_year"] },
    { "for": "Wife", "item": "Smartwatch", "tags": ["tech", "birthday", "new_year"] },
    { "for": "Wife", "item": "Luxury bath bomb kit", "tags": ["spa", "christmas", "relaxation"] },
    { "for": "Wife", "item": "Handmade jewelry from local artist", "tags": ["birthday", "unique", "valentine"] },
    { "for": "Wife", "item": "Romantic picnic basket", "tags": ["anniversary", "valentine", "summer"] },
    { "for": "Wife", "item": "A surprise love note box", "tags": ["valentine", "anniversary", "random"] },
    { "for": "Wife", "item": "Customized illustration of you both", "tags": ["anniversary", "art", "valentine"] },
    { "for": "Husband", "item": "Smartwatch or fitness tracker", "tags": ["birthday", "tech", "new_year"] },
    { "for": "Husband", "item": "Personalized leather wallet", "tags": ["anniversary", "birthday", "practical"] },
    { "for": "Husband", "item": "Favorite whiskey or craft beer set", "tags": ["birthday", "christmas", "relaxation"] },
    { "for": "Husband", "item": "Wireless earbuds", "tags": ["tech", "birthday", "new_year"] },
    { "for": "Husband", "item": "Gaming accessories", "tags": ["gaming", "birthday", "christmas"] },
    { "for": "Husband", "item": "Sports jersey from his favorite team", "tags": ["birthday", "sport", "casual"] },
    { "for": "Husband", "item": "Customized engraved keychain", "tags": ["anniversary", "valentine", "everyday"] },
    { "for": "Husband", "item": "Barbecue grill tools", "tags": ["outdoor", "summer", "christmas"] },
    { "for": "Husband", "item": "Adventure experience (paintball, karting)", "tags": ["activity", "birthday", "fun"] },
    { "for": "Husband", "item": "A surprise date night", "tags": ["anniversary", "valentine", "romantic"] },
    { "for": "Husband", "item": "Leather jacket", "tags": ["fashion", "christmas", "birthday"] },
    { "for": "Husband", "item": "Personalized beer mug", "tags": ["birthday", "fun", "christmas"] },
    { "for": "Husband", "item": "Tool kit box", "tags": ["practical", "home", "birthday"] },
    { "for": "Husband", "item": "A smartwatch strap collection", "tags": ["tech", "fashion", "birthday"] },
    { "for": "Husband", "item": "Bluetooth speaker", "tags": ["music", "tech", "birthday"] },
    { "for": "Husband", "item": "Customized phone dock", "tags": ["tech", "desk", "birthday"] },
    { "for": "Husband", "item": "Camping gear set", "tags": ["outdoor", "adventure", "summer"] },
    { "for": "Husband", "item": "Favorite comic book collection", "tags": ["fun", "nostalgia", "birthday"] },
    { "for": "Husband", "item": "Luxury shaving kit", "tags": ["grooming", "anniversary", "christmas"] },
    { "for": "Husband", "item": "Cooking tools for men", "tags": ["fun", "practical", "home"] },
    { "for": "Husband", "item": "Personalized key organizer", "tags": ["tech", "organization", "everyday"] },
    { "for": "Husband", "item": "Noise-canceling headphones", "tags": ["tech", "music", "travel"] },
    { "for": "Husband", "item": "Weekend road trip", "tags": ["anniversary", "holiday", "romantic"] },
    { "for": "Husband", "item": "Pocket watch with engraving", "tags": ["anniversary", "classic", "luxury"] },
    { "for": "Husband", "item": "Coffee brewing kit", "tags": ["coffee", "home", "christmas"] },
    { "for": "Husband", "item": "Sunglasses with case", "tags": ["fashion", "summer", "travel"] },
    { "for": "Husband", "item": "Digital gift card", "tags": ["flexible", "birthday", "random"] },
    { "for": "Husband", "item": "Customized t-shirt with inside joke", "tags": ["funny", "friendship", "birthday"] },
    { "for": "Husband", "item": "Car accessories kit", "tags": ["automotive", "birthday", "new_year"] },
    { "for": "Husband", "item": "Personalized notebook", "tags": ["work", "organization", "casual"] },
    { "for": "Parents", "item": "Family photo frame or canvas print", "tags": ["home", "anniversary", "christmas"] },
    { "for": "Parents", "item": "Massage chair cushion", "tags": ["comfort", "health", "birthday"] },
    { "for": "Parents", "item": "Tea or coffee gift set", "tags": ["christmas", "home", "thank_you"] },
    { "for": "Parents", "item": "Digital photo frame with family pictures", "tags": ["tech", "anniversary", "memory"] },
    { "for": "Parents", "item": "Customized blanket", "tags": ["home", "comfort", "birthday"] },
    { "for": "Parents", "item": "Home plant or bonsai tree", "tags": ["home", "relaxation", "thank_you"] },
    { "for": "Parents", "item": "Memory journal", "tags": ["sentimental", "anniversary", "birthday"] },
    { "for": "Parents", "item": "Dinner at their favorite restaurant", "tags": ["anniversary", "birthday", "thank_you"] },
    { "for": "Parents", "item": "Health and wellness gift basket", "tags": ["health", "thank_you", "birthday"] },
    { "for": "Parents", "item": "Matching pajamas set", "tags": ["christmas", "comfort", "anniversary"] },
    { "for": "Parents", "item": "Customized pillow with family photo", "tags": ["home", "memory", "birthday"] },
    { "for": "Parents", "item": "Cooking class for parents", "tags": ["activity", "fun", "anniversary"] },
    { "for": "Parents", "item": "Subscription to movie streaming", "tags": ["entertainment", "birthday", "relaxation"] },
    { "for": "Parents", "item": "Classic music CD collection", "tags": ["music", "nostalgia", "birthday"] },
    { "for": "Parents", "item": "Electric kettle set", "tags": ["home", "practical", "birthday"] },
    { "for": "Parents", "item": "Heated blanket", "tags": ["comfort", "winter", "health"] },
    { "for": "Parents", "item": "Photo calendar with family memories", "tags": ["new_year", "home", "memory"] },
    { "for": "Parents", "item": "Garden tools kit", "tags": ["outdoor", "hobby", "birthday"] },
    { "for": "Parents", "item": "Personalized mug pair", "tags": ["anniversary", "home", "christmas"] },
    { "for": "Parents", "item": "Luxury tea set", "tags": ["birthday", "relaxation", "home"] },
    { "for": "Parents", "item": "Cookbook with favorite cuisines", "tags": ["home", "cooking", "birthday"] },
    { "for": "Parents", "item": "Customized photo album", "tags": ["memory", "anniversary", "birthday"] },
    { "for": "Parents", "item": "Subscription to wellness magazine", "tags": ["health", "birthday", "new_year"] },
    { "for": "Parents", "item": "Smart home assistant", "tags": ["tech", "home", "christmas"] },
    { "for": "Parents", "item": "A weekend retreat", "tags": ["holiday", "anniversary", "thank_you"] },
    { "for": "Parents", "item": "Scent diffuser set", "tags": ["home", "relaxation", "christmas"] },
    { "for": "Parents", "item": "Personalized cutting board", "tags": ["kitchen", "home", "anniversary"] },
    { "for": "Parents", "item": "Cozy slippers", "tags": ["comfort", "winter", "birthday"] },
    { "for": "Parents", "item": "Vitamin and health supplement box", "tags": ["health", "new_year", "birthday"] },
    { "for": "Parents", "item": "Family tree wall art", "tags": ["memory", "home", "anniversary"] },
    { "for": "Children", "item": "LEGO or building blocks set", "tags": ["birthday", "creative", "fun"] },
    { "for": "Children", "item": "Stuffed animal", "tags": ["birthday", "comfort", "christmas"] },
    { "for": "Children", "item": "Storybook or picture book", "tags": ["educational", "bedtime", "birthday"] },
    { "for": "Children", "item": "Educational toy kit", "tags": ["learning", "christmas", "fun"] },
    { "for": "Children", "item": "Art and craft supplies", "tags": ["creative", "birthday", "school"] },
    { "for": "Children", "item": "Puzzle game", "tags": ["brain", "educational", "birthday"] },
    { "for": "Children", "item": "Outdoor play set", "tags": ["summer", "activity", "birthday"] },
    { "for": "Children", "item": "Personalized backpack", "tags": ["school", "birthday", "practical"] },
    { "for": "Children", "item": "New bicycle or scooter", "tags": ["birthday", "outdoor", "new_year"] },
    { "for": "Children", "item": "Kids smartwatch", "tags": ["tech", "birthday", "safety"] },
    { "for": "Children", "item": "Dinosaur figure set", "tags": ["fun", "birthday", "collectible"] },
    { "for": "Children", "item": "Kids cooking set", "tags": ["learning", "fun", "family_time"] },
    { "for": "Children", "item": "Glow-in-the-dark stars for room", "tags": ["home", "creative", "birthday"] },
    { "for": "Children", "item": "Musical instrument toy", "tags": ["music", "learning", "birthday"] },
    { "for": "Children", "item": "Animated character costume", "tags": ["fun", "party", "birthday"] },
    { "for": "Children", "item": "Pop-up storybook", "tags": ["reading", "educational", "birthday"] },
    { "for": "Children", "item": "Kids tent or playhouse", "tags": ["home", "fun", "imagination"] },
    { "for": "Children", "item": "Coloring book set", "tags": ["creative", "school", "birthday"] },
    { "for": "Children", "item": "Children’s camera", "tags": ["tech", "creative", "birthday"] },
    { "for": "Children", "item": "Toy train set", "tags": ["classic", "fun", "birthday"] },
    { "for": "Children", "item": "Interactive robot toy", "tags": ["tech", "learning", "christmas"] },
    { "for": "Children", "item": "Watercolor paint kit", "tags": ["creative", "art", "birthday"] },
    { "for": "Children", "item": "Educational tablet for kids", "tags": ["tech", "learning", "new_year"] },
    { "for": "Children", "item": "Stuffed unicorn or fantasy animal", "tags": ["comfort", "fun", "birthday"] },
    { "for": "Children", "item": "Mini science experiment kit", "tags": ["learning", "fun", "educational"] },
    { "for": "Children", "item": "Magic trick set", "tags": ["fun", "party", "birthday"] },
    { "for": "Children", "item": "Remote control car", "tags": ["tech", "fun", "birthday"] },
    { "for": "Children", "item": "Animal puzzle blocks", "tags": ["educational", "fun", "home"] },
    { "for": "Children", "item": "Toy doctor kit", "tags": ["learning", "pretend_play", "birthday"] },
    { "for": "Children", "item": "Personalized night light", "tags": ["home", "comfort", "birthday"] },
    { "for": "Siblings", "item": "Funny T-shirt or hoodie", "tags": ["casual", "birthday", "funny"] },
    { "for": "Siblings", "item": "Customized mug", "tags": ["home", "fun", "birthday"] },
    { "for": "Siblings", "item": "Board game or card game", "tags": ["fun", "family_time", "christmas"] },
    { "for": "Siblings", "item": "Movie night gift box", "tags": ["fun", "entertainment", "birthday"] },
    { "for": "Siblings", "item": "Bluetooth speaker", "tags": ["music", "tech", "birthday"] },
    { "for": "Siblings", "item": "Photo collage frame", "tags": ["memory", "home", "birthday"] },
    { "for": "Siblings", "item": "Favorite snack box", "tags": ["fun", "birthday", "random"] },
    { "for": "Siblings", "item": "Matching accessories", "tags": ["funny", "fashion", "birthday"] },
    { "for": "Siblings", "item": "Subscription to streaming service", "tags": ["entertainment", "birthday", "relaxation"] },
    { "for": "Siblings", "item": "DIY craft set", "tags": ["creative", "fun", "home"] },
    { "for": "Siblings", "item": "Personalized phone case", "tags": ["tech", "birthday", "style"] },
    { "for": "Siblings", "item": "Memory scrapbook", "tags": ["sentimental", "birthday", "anniversary"] },
    { "for": "Siblings", "item": "Laptop sleeve", "tags": ["tech", "school", "birthday"] },
    { "for": "Siblings", "item": "Smartwatch strap set", "tags": ["fashion", "tech", "birthday"] },
    { "for": "Siblings", "item": "Custom cartoon portrait", "tags": ["art", "fun", "birthday"] },
    { "for": "Siblings", "item": "Portable mini speaker", "tags": ["music", "travel", "fun"] },
    { "for": "Siblings", "item": "Favorite band poster", "tags": ["music", "home", "birthday"] },
    { "for": "Siblings", "item": "Reusable water bottle", "tags": ["health", "school", "new_year"] },
    { "for": "Siblings", "item": "A pair of cozy socks", "tags": ["comfort", "christmas", "birthday"] },
    { "for": "Siblings", "item": "Jigsaw puzzle", "tags": ["fun", "brain", "home"] },
    { "for": "Siblings", "item": "Digital gift card", "tags": ["flexible", "birthday", "random"] },
    { "for": "Siblings", "item": "Instant camera", "tags": ["photo", "creative", "birthday"] },
    { "for": "Siblings", "item": "Mini indoor plant", "tags": ["home", "aesthetic", "birthday"] },
    { "for": "Siblings", "item": "Fitness tracker band", "tags": ["health", "tech", "new_year"] },
    { "for": "Siblings", "item": "Wireless charging pad", "tags": ["tech", "practical", "birthday"] },
    { "for": "Siblings", "item": "Funny calendar", "tags": ["office", "funny", "new_year"] },
    { "for": "Siblings", "item": "A surprise snack subscription", "tags": ["fun", "food", "random"] },
    { "for": "Siblings", "item": "Cute stationery set", "tags": ["school", "art", "birthday"] },
    { "for": "Siblings", "item": "Travel toiletry kit", "tags": ["travel", "practical", "birthday"] },
    { "for": "Siblings", "item": "Scented candle jar", "tags": ["relaxation", "home", "birthday"] },
    { "for": "Coworkers", "item": "Desk plant", "tags": ["office", "relaxation", "birthday"] },
    { "for": "Coworkers", "item": "Coffee mug with quote", "tags": ["office", "funny", "birthday"] },
    { "for": "Coworkers", "item": "Portable charger", "tags": ["tech", "travel", "practical"] },
    { "for": "Coworkers", "item": "Notebook or planner", "tags": ["work", "organization", "new_year"] },
    { "for": "Coworkers", "item": "Stress relief toy", "tags": ["office", "fun", "mental_health"] },
    { "for": "Coworkers", "item": "Gift card for lunch or coffee", "tags": ["flexible", "thank_you", "birthday"] },
    { "for": "Coworkers", "item": "Mini lamp or office decor", "tags": ["home", "aesthetic", "work"] },
    { "for": "Coworkers", "item": "Reusable water bottle", "tags": ["health", "office", "new_year"] },
    { "for": "Coworkers", "item": "Mouse pad with design", "tags": ["work", "fun", "practical"] },
    { "for": "Coworkers", "item": "A handwritten thank-you note", "tags": ["thank_you", "casual", "random"] },
    { "for": "Coworkers", "item": "Ergonomic wrist rest pad", "tags": ["health", "work", "practical"] },
    { "for": "Coworkers", "item": "Customized nameplate", "tags": ["office", "personalized", "thank_you"] },
    { "for": "Coworkers", "item": "Tea sampler box", "tags": ["relaxation", "thank_you", "birthday"] },
    { "for": "Coworkers", "item": "USB desk fan", "tags": ["office", "tech", "summer"] },
    { "for": "Coworkers", "item": "Mini calendar stand", "tags": ["office", "organization", "new_year"] },
    { "for": "Coworkers", "item": "Office snack jar", "tags": ["fun", "thank_you", "random"] },
    { "for": "Coworkers", "item": "Desk organizer tray", "tags": ["work", "organization", "birthday"] },
    { "for": "Coworkers", "item": "Scented candle", "tags": ["relaxation", "home", "office"] },
    { "for": "Coworkers", "item": "Wireless mouse", "tags": ["tech", "work", "practical"] },
    { "for": "Coworkers", "item": "Sticky notes set", "tags": ["office", "fun", "practical"] },
    { "for": "Coworkers", "item": "Motivational poster", "tags": ["office", "positive", "thank_you"] },
    { "for": "Coworkers", "item": "Desk photo frame", "tags": ["office", "personal", "birthday"] },
    { "for": "Coworkers", "item": "Reusable coffee cup", "tags": ["eco_friendly", "work", "new_year"] },
    { "for": "Coworkers", "item": "Keychain with initials", "tags": ["personalized", "thank_you", "birthday"] },
    { "for": "Coworkers", "item": "Cable organizer", "tags": ["tech", "practical", "office"] },
    { "for": "Coworkers", "item": "Mini Bluetooth speaker", "tags": ["music", "office", "fun"] },
    { "for": "Coworkers", "item": "Plant-growing kit", "tags": ["home", "eco_friendly", "relaxation"] },
    { "for": "Coworkers", "item": "Office trivia card game", "tags": ["fun", "team_building", "random"] },
    { "for": "Coworkers", "item": "Insulated lunch box", "tags": ["work", "practical", "birthday"] },
    { "for": "Coworkers", "item": "Book of positive quotes", "tags": ["inspiration", "office", "thank_you"] },
    { "for": "New Parents", "item": "Baby essentials basket (diapers, wipes, lotion)", "tags": ["Baby Shower", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Personalized baby blanket", "tags": ["Baby Shower", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Photo album for baby milestones", "tags": ["Memory Gift", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Meal delivery subscription", "tags": ["Practical Gift", "Postpartum Support"] },
    { "for": "New Parents", "item": "Relaxation gift box for mom", "tags": ["Self-care", "New Mom Gift"] },
    { "for": "New Parents", "item": "Matching outfit for baby and parents", "tags": ["Family Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Portable baby monitor", "tags": ["Safety Gift", "Tech Gift"] },
    { "for": "New Parents", "item": "Spa voucher for mom", "tags": ["Relaxation", "Postpartum Care"] },
    { "for": "New Parents", "item": "Baby milestone cards", "tags": ["Memory Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Custom name nursery wall art", "tags": ["Home Decor", "Baby Shower"] },
    { "for": "New Parents", "item": "White noise machine for baby", "tags": ["Sleep Gift", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Ergonomic baby carrier", "tags": ["Practical Gift", "Travel Gift"] },
    { "for": "New Parents", "item": "Handprint and footprint kit", "tags": ["Memory Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Baby bath set", "tags": ["Newborn Arrival", "Care Gift"] },
    { "for": "New Parents", "item": "Customized baby storybook", "tags": ["Memory Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Diaper bag backpack", "tags": ["Practical Gift", "Travel Gift"] },
    { "for": "New Parents", "item": "Parenting guidebook", "tags": ["New Parent Gift", "Educational"] },
    { "for": "New Parents", "item": "Baby feeding starter kit", "tags": ["Practical Gift", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Customized baby name pillow", "tags": ["Nursery Decor", "Baby Shower"] },
    { "for": "New Parents", "item": "Sleep sound projector", "tags": ["Sleep Gift", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Baby clothes gift set", "tags": ["Baby Shower", "Newborn Arrival"] },
    { "for": "New Parents", "item": "Memory keepsake box", "tags": ["Memory Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Mini photo printer", "tags": ["Memory Gift", "New Parent Gift"] },
    { "for": "New Parents", "item": "Baby milestone blanket", "tags": ["Photography Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Breastfeeding support pillow", "tags": ["Comfort Gift", "New Mom Gift"] },
    { "for": "New Parents", "item": "Personalized baby bib set", "tags": ["Baby Shower", "Practical Gift"] },
    { "for": "New Parents", "item": "Soft lullaby toy", "tags": ["Sleep Gift", "Baby Shower"] },
    { "for": "New Parents", "item": "Baby hand-knit shoes", "tags": ["Gift of Love", "Baby Shower"] },
    { "for": "New Parents", "item": "Customized family portrait illustration", "tags": ["Memory Gift", "Family Gift"] },
    { "for": "New Parents", "item": "Subscription for baby diapers", "tags": ["Practical Gift", "New Parent Gift"] },
    { "for": "Others", "item": "Gift card for online shopping", "tags": ["Birthday", "Christmas", "Anytime"] },
    { "for": "Others", "item": "Handmade craft item", "tags": ["Birthday", "Friendship", "Appreciation"] },
    { "for": "Others", "item": "Donation to charity in their name", "tags": ["Christmas", "Memorial", "Thank You"] },
    { "for": "Others", "item": "Customized notebook with quote", "tags": ["Office Gift", "Birthday"] },
    { "for": "Others", "item": "Portable phone stand", "tags": ["Practical Gift", "Birthday"] },
    { "for": "Others", "item": "Self-care gift set", "tags": ["Wellness Gift", "Christmas"] },
    { "for": "Others", "item": "Reusable tote bag", "tags": ["Eco-friendly Gift", "Birthday"] },
    { "for": "Others", "item": "Mini succulent plant", "tags": ["Housewarming", "Office Gift"] },
    { "for": "Others", "item": "Mystery box surprise", "tags": ["Birthday", "Just Because"] },
    { "for": "Others", "item": "Cute stationery pack", "tags": ["Office Gift", "Birthday"] },
    { "for": "Others", "item": "Aromatherapy essential oil set", "tags": ["Wellness Gift", "Christmas"] },
    { "for": "Others", "item": "Customized keychain", "tags": ["Thank You", "Birthday"] },
    { "for": "Others", "item": "DIY candle kit", "tags": ["Creative Gift", "Christmas"] },
    { "for": "Others", "item": "Eco-friendly bamboo cutlery set", "tags": ["Sustainability", "Birthday"] },
    { "for": "Others", "item": "Insulated water bottle", "tags": ["Fitness Gift", "Everyday Use"] },
    { "for": "Others", "item": "Personalized calendar", "tags": ["New Year", "Office Gift"] },
    { "for": "Others", "item": "Bluetooth tracker for keys or wallet", "tags": ["Tech Gift", "Practical Gift"] },
    { "for": "Others", "item": "Digital gift card (Amazon, Spotify, Steam)", "tags": ["Birthday", "Anytime"] },
    { "for": "Others", "item": "Small photo frame", "tags": ["Home Decor", "Thank You"] },
    { "for": "Others", "item": "Mini book of quotes", "tags": ["Inspiration", "Everyday Gift"] },
    { "for": "Others", "item": "Customized fridge magnets", "tags": ["Souvenir", "Birthday"] },
    { "for": "Others", "item": "Notebook with handmade paper", "tags": ["Creative Gift", "Office Gift"] },
    { "for": "Others", "item": "Tea sampler set", "tags": ["Relaxation", "Christmas"] },
    { "for": "Others", "item": "Coffee lover’s gift box", "tags": ["Birthday", "Office Gift"] },
    { "for": "Others", "item": "Travel-size toiletry kit", "tags": ["Travel Gift", "Birthday"] },
    { "for": "Others", "item": "Small puzzle toy", "tags": ["Brain Teaser", "Christmas"] },
    { "for": "Others", "item": "LED night light", "tags": ["Home Decor", "Christmas"] },
    { "for": "Others", "item": "Portable mini humidifier", "tags": ["Health Gift", "Office Decor"] },
    { "for": "Others", "item": "Reusable stainless steel straw set", "tags": ["Eco Gift", "Practical Gift"] },
    { "for": "Others", "item": "Digital thank-you card", "tags": ["Appreciation", "Farewell"] }
];
