export type Plant = {
  name: string;
  scientificName: string;
  family: string;
  order: string;
  benefits: string;
  characteristics: string;
  imageSearchTerm: string;
};

export const PLANT_DATA: Plant[] = [
  {
    name: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    family: 'Lamiaceae',
    order: 'Lamiales',
    benefits: 'Known for its calming aroma, used in aromatherapy to reduce stress and anxiety. Its oil has antiseptic and anti-inflammatory properties.',
    characteristics: 'Features spikes of purple flowers, silvery-green leaves, and a sweet, floral fragrance. It is a hardy, drought-tolerant perennial.',
    imageSearchTerm: 'lavender field',
  },
  {
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    family: 'Asteraceae',
    order: 'Asterales',
    benefits: 'Seeds are a nutritious food source rich in healthy fats and vitamins. Sunflowers are also used for producing vegetable oil and for phytoremediation to extract toxins from soil.',
    characteristics: 'Large, daisy-like flower head that tracks the sun (heliotropism). It has a tall, sturdy stem and can grow to significant heights.',
    imageSearchTerm: 'sunflower',
  },
  {
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    family: 'Asphodelaceae',
    order: 'Asparagales',
    benefits: 'The gel inside its leaves is widely used to soothe sunburns, heal wounds, and moisturize skin. It is also consumed for digestive health.',
    characteristics: 'A succulent plant with thick, fleshy, serrated leaves that grow in a rosette pattern. It stores water in its leaves.',
    imageSearchTerm: 'aloe vera plant',
  },
  {
    name: 'Ginkgo Biloba',
    scientificName: 'Ginkgo biloba',
    family: 'Ginkgoidae',
    order: 'Ginkgoales',
    benefits: 'Often called a "living fossil." Its leaf extract is used in supplements to improve memory and cognitive function, though scientific evidence is mixed.',
    characteristics: 'A unique tree with no close living relatives. It has distinctive fan-shaped leaves that turn a brilliant yellow in the fall.',
    imageSearchTerm: 'ginkgo leaf',
  },
  {
    name: 'Venus Flytrap',
    scientificName: 'Dionaea muscipula',
    family: 'Droseraceae',
    order: 'Caryophyllales',
    benefits: 'Primarily a subject of fascination and study in botany. It helps control insect populations in its native boggy environment.',
    characteristics: 'A carnivorous plant famous for its hinged, trap-like leaves that snap shut when trigger hairs are touched, capturing insects for nutrients.',
    imageSearchTerm: 'venus flytrap',
  },
  {
    name: 'Bamboo',
    scientificName: 'Bambusoideae (subfamily)',
    family: 'Poaceae',
    order: 'Poales',
    benefits: 'Extremely versatile. Used as a sustainable building material, for making textiles, paper, and as a food source (bamboo shoots). It also releases 35% more oxygen than equivalent trees.',
    characteristics: 'A type of grass characterized by its hollow, jointed stems called culms. It is one of the fastest-growing plants in the world.',
    imageSearchTerm: 'bamboo forest',
  },
  {
    name: 'Giant Sequoia',
    scientificName: 'Sequoiadendron giganteum',
    family: 'Cupressaceae',
    order: 'Pinales',
    benefits: 'Ecologically vital, providing habitat for wildlife. Its sheer scale and age inspire awe and promote tourism and conservation efforts.',
    characteristics: 'The world\'s most massive single trees by volume. They have a fibrous, furrowed, reddish-brown bark and are incredibly long-lived.',
    imageSearchTerm: 'giant sequoia tree',
  },
  {
    name: 'Rafflesia',
    scientificName: 'Rafflesia arnoldii',
    family: 'Rafflesiaceae',
    order: 'Malpighiales',
    benefits: 'Primarily an object of scientific and touristic interest due to its unique biology. It has some traditional medicinal uses, but they are not widely proven.',
    characteristics: 'Produces the largest single flower on Earth. It is a parasitic plant with no visible leaves, roots, or stem, and emits a foul odor of rotting flesh to attract pollinators.',
    imageSearchTerm: 'rafflesia flower',
  },
  {
    name: 'Coffee Plant',
    scientificName: 'Coffea arabica',
    family: 'Rubiaceae',
    order: 'Gentianales',
    benefits: 'The source of coffee beans, which are roasted to produce one of the world\'s most popular beverages. The drink is prized for its caffeine content and stimulating effects.',
    characteristics: 'A woody perennial shrub with glossy, dark-green leaves. It produces white, fragrant flowers that are followed by red or purple fruits called "cherries."',
    imageSearchTerm: 'coffee plant cherry',
  },
  {
    name: 'Cacao Tree',
    scientificName: 'Theobroma cacao',
    family: 'Malvaceae',
    order: 'Malvales',
    benefits: 'The source of cacao beans, which are processed to make cocoa and chocolate. Cacao is rich in antioxidants and minerals.',
    characteristics: 'A small evergreen tree that grows in tropical regions. Its large, pod-like fruits grow directly from the trunk and main branches (cauliflory).',
    imageSearchTerm: 'cacao pod',
  },
  {
    name: 'Welwitschia',
    scientificName: 'Welwitschia mirabilis',
    family: 'Welwitschiaceae',
    order: 'Welwitschiales',
    benefits: 'Of extreme scientific interest due to its unique morphology and longevity. It is a symbol of resilience in the harsh Namib desert.',
    characteristics: 'A bizarre desert plant consisting of a woody stem, a taproot, and only two leaves that grow continuously throughout its entire life, which can be over 1,500 years.',
    imageSearchTerm: 'welwitschia plant',
  },
  {
    name: 'Pitcher Plant',
    scientificName: 'Nepenthes',
    family: 'Nepenthaceae',
    order: 'Caryophyllales',
    benefits: 'A carnivorous plant that controls insect populations. It is a popular ornamental plant for collectors of exotic flora.',
    characteristics: 'Features a modified leaf that forms a pitfall trap—a fluid-filled pitcher that drowns insects. The rim of the pitcher is often slippery to prevent escape.',
    imageSearchTerm: 'pitcher plant',
  },
  {
    name: 'Baobab Tree',
    scientificName: 'Adansonia',
    family: 'Malvaceae',
    order: 'Malvales',
    benefits: 'Known as the "Tree of Life." Its fruit is a nutrient-rich superfood, its bark can be made into rope, and its massive trunk stores large amounts of water.',
    characteristics: 'A prehistoric-looking tree with an exceptionally thick, bottle-shaped trunk and sparse, root-like branches. It can live for thousands of years.',
    imageSearchTerm: 'baobab tree',
  },
  {
    name: 'Dragon\'s Blood Tree',
    scientificName: 'Dracaena cinnabari',
    family: 'Asparagaceae',
    order: 'Asparagales',
    benefits: 'Produces a dark red resin, known as "dragon\'s blood," which has been used for centuries as a dye, varnish, incense, and in traditional medicine.',
    characteristics: 'An iconic, umbrella-shaped tree native to the Socotra archipelago. Its unique shape is the result of a dense branching pattern.',
    imageSearchTerm: 'dragons blood tree',
  },
  {
    name: 'Eucalyptus',
    scientificName: 'Eucalyptus',
    family: 'Myrtaceae',
    order: 'Myrtales',
    benefits: 'The oil from its leaves has antiseptic properties and is used in cough drops and inhalants. It is the primary food source for koalas.',
    characteristics: 'A fast-growing evergreen tree native to Australia. Known for its aromatic leaves and bark that often peels off in strips.',
    imageSearchTerm: 'eucalyptus tree',
  },
  {
    name: 'Quaking Aspen',
    scientificName: 'Populus tremuloides',
    family: 'Salicaceae',
    order: 'Malpighiales',
    benefits: 'Important for wildlife habitat and soil stabilization. The bark contains salicin, which has properties similar to aspirin.',
    characteristics: 'Famous for its leaves that tremble or "quake" in the slightest breeze. A single colony can form a massive clonal organism, connected by a single root system.',
    imageSearchTerm: 'aspen trees fall',
  },
  {
    name: 'Orchid',
    scientificName: 'Orchidaceae',
    family: 'Orchidaceae',
    order: 'Asparagales',
    benefits: 'Highly valued as ornamental plants. The Vanilla orchid produces the vanilla bean, a globally important flavoring.',
    characteristics: 'One of the largest families of flowering plants. Orchids are known for their complex and often bizarrely shaped flowers, which have evolved to attract specific pollinators.',
    imageSearchTerm: 'orchid flower',
  },
  {
    name: 'Sensitive Plant',
    scientificName: 'Mimosa pudica',
    family: 'Fabaceae',
    order: 'Fabales',
    benefits: 'Mainly grown for its curiosity value. It demonstrates a rapid plant movement known as thigmonasty.',
    characteristics: 'A creeping plant known for its unique response to touch. Its leaves fold inward and droop when touched or shaken, re-opening a few minutes later.',
    imageSearchTerm: 'mimosa pudica',
  },
  {
    name: 'Cotton',
    scientificName: 'Gossypium',
    family: 'Malvaceae',
    order: 'Malvales',
    benefits: 'The world\'s most important natural fiber. Used to make a vast range of textiles. Cottonseed oil is used in food products.',
    characteristics: 'A shrub that produces a protective capsule, or "boll," filled with fluffy fibers. These fibers are harvested to be spun into yarn.',
    imageSearchTerm: 'cotton plant',
  },
  {
    name: 'Redwood',
    scientificName: 'Sequoia sempervirens',
    family: 'Cupressaceae',
    order: 'Pinales',
    benefits: 'Plays a crucial role in its ecosystem by capturing moisture from coastal fog. Its wood is highly resistant to decay.',
    characteristics: 'The tallest trees on Earth, capable of reaching over 380 feet (115 meters). They have a slender, conical shape and thrive in the coastal fog belt.',
    imageSearchTerm: 'redwood forest',
  }
];
