version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # You can add other necessary environment variables here.
      # For example, if you have API keys in a .env file:
    env_file:
      - .env
    container_name: randomizer-app
