import { Header } from "@/components/header";

export default function TermsOfServicePage() {
    return (
        <div className="flex flex-col items-center justify-start min-h-screen p-4 md:p-8 pt-12 md:pt-16">
            <Header />
            <main className="w-full max-w-4xl mx-auto mt-6 bg-card text-card-foreground p-6 md:p-10 rounded-lg shadow-md prose dark:prose-invert">
                <h1>Terms of Service (ToS) for Randomizer.fun</h1>
                <p><em>Last Updated: October 11, 2025</em></p>

                <p>Please read these Terms of Service ("Terms," "ToS") carefully before using the Randomizer.fun website (the "Service") operated by [Your Name/Company Name] ("Us," "We," or "Our").</p>

                <p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service.</p>

                <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.</p>

                <h2>1. The Service and Its Use</h2>
                <p>Randomizer.fun is an online utility that provides various randomization tools, generators, and shufflers ("Tools").</p>

                <h3>A. Tool Usage</h3>
                <p>The Tools provided are for informational, entertainment, and utility purposes only. We make no warranty or guarantee regarding the accuracy, reliability, or fairness of any outcome generated by the Tools (e.g., dice rolls, list shuffles, lottery numbers, etc.). Users rely on the generated results at their own risk.</p>

                <h3>B. User Accounts</h3>
                <p><strong>Registration:</strong> To access protected features (such as the YouTube randomizer or specific theme settings), you must register for an account using Firebase Authentication (e.g., Google Sign-in).</p>
                <p><strong>Account Responsibility:</strong> You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your account. You agree not to disclose your password to any third party.</p>

                <h2>2. User Obligations and Prohibitions</h2>
                <p>You agree not to use the Service:</p>
                <ul>
                    <li><strong>Unlawful Use:</strong> In any way that violates any applicable national or international law or regulation.</li>
                    <li><strong>Harmful Content:</strong> To transmit or input data that is harmful, threatening, defamatory, obscene, or racially/ethnically objectionable.</li>
                    <li><strong>Malicious Activity:</strong> To interfere with, disrupt, or create an undue burden on the Service or the networks or services connected to the Service.</li>
                    <li><strong>Commercial Use:</strong> For high-volume commercial use without explicit written permission.</li>
                </ul>

                <h2>3. Intellectual Property</h2>
                <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of [Your Name/Company Name] and its licensors. The Tools and the website design are protected by copyright, trademark, and other laws.</p>

                <h2>4. Termination</h2>
                <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including without limitation if you breach the Terms.</p>
                <p>Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may discontinue using the Service or contact us for account deletion.</p>

                <h2>5. Limitation of Liability</h2>
                <p>In no event shall [Your Name/Company Name], nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:</p>
                <ul>
                    <li>Your access to or use of, or inability to access or use, the Service.</li>
                    <li>Any content obtained from the Service.</li>
                    <li>Unauthorized access, use, or alteration of your transmissions or content.</li>
                </ul>

                <h2>6. Disclaimer</h2>
                <p>Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.</p>

                <h2>7. Governing Law</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of [Your Country/State], without regard to its conflict of law provisions.</p>

                <h2>8. Changes to These Terms</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days' notice prior to any new terms taking effect. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.</p>

                <h2>9. Contact Us</h2>
                <p>If you have any questions about these Terms, please contact us:</p>
                <p>Email: [Your active email address, e.g., support@randomizer.fun]</p>
            </main>
        </div>
    );
}
