// 'use server';

type QuestionType = 'truth' | 'dare';

const TRUTH_QUESTIONS = [
  "If you could have dinner with any historical figure, who would it be and why?",
  "What is the most embarrassing thing that has ever happened to you?",
  "What is a secret you've never told anyone?",
  "What is your biggest fear?",
  "What is the biggest lie you have ever told?",
  "What is something you are self-conscious about?",
  "Have you ever cheated on a test?",
  "What is the most childish thing you still do?",
  "What's the worst thing you've ever said to someone?",
  "What is your guilty pleasure?",
  "What's one thing you'd change about your appearance if you could?",
  "Who is your secret crush?",
  "When was the last time you cried and why?",
  "What is the biggest regret you have?",
  "What's the most trouble you've ever gotten into?",
  "What is one thing you would do if you knew there were no consequences?",
  "What's the most ridiculous thing you've bought?",
  "If you had to switch lives with someone for a day, who would it be?",
  "What's a weird food combination you secretly enjoy?",
  "Have you ever stalked someone on social media?",
  "What's a movie that made you cry?",
  "What's the most awkward date you've ever been on?",
  "What's an irrational fear you have?",
  "Have you ever peed in a swimming pool?",
  "What's the longest you've gone without showering?",
  "What's a bad habit you can't seem to break?",
  "What's the most embarrassing song on your phone?",
  "Have you ever pretended to be sick to get out of something?",
  "What's a nickname you have that you hate?",
  "What's something you're terrible at?",
  "Have you ever been caught picking your nose?",
  "What's the weirdest dream you've ever had?",
  "What's a secret talent you have?",
  "What's the most expensive thing you've broken?",
  "Have you ever re-gifted a present?",
  "What's one thing you're scared of in a relationship?",
  "What's a password you've used that was really dumb?",
  "What's the most embarrassing thing your parents have caught you doing?",
  "If you could trade places with a friend for a day, who would it be?",
  "What's something you've done that you hope your parents never find out about?",
  "What's the biggest misconception people have about you?",
  "What's a TV show you're secretly addicted to?",
  "Have you ever practiced kissing in a mirror?",
  "What's the silliest thing you've cried about?",
  "What's the strangest thing you've ever eaten?",
  "Who was your first celebrity crush?",
  "What's a word you can never spell correctly on the first try?",
  "Have you ever had a crush on a friend's partner?",
  "What's the most embarrassing text you've accidentally sent to the wrong person?",
  "What's a common piece of advice that you think is total nonsense?"
];

const DARES = [
  "Do an impersonation of your favorite celebrity.",
  "Speak in a different accent for the next 3 rounds.",
  "Let the person to your right draw a mustache on your face with a pen.",
  "Post an old, embarrassing photo of yourself on social media.",
  "Call a random number and try to have a conversation for 1 minute.",
  "Sing a song chosen by the group, as loudly as you can.",
  "Do 20 pushups or sit-ups.",
  "Let someone tickle you for 30 seconds without laughing.",
  "Eat a spoonful of a condiment (like mustard, ketchup, or hot sauce).",
  "Go outside and yell 'I love [random object]!' at the top of your lungs.",
  "Wear your socks on your hands for the rest of the game.",
  "Talk and act like a robot until your next turn.",
  "Let the group give you a new nickname that you have to answer to.",
  "Do your best runway walk.",
  "Try to juggle three items chosen by the group.",
  "Use a cheesy pickup line on someone in the room.",
  "Let someone else post a status on your social media account.",
  "Try to lick your elbow.",
  "Hold a funny face for the next two rounds.",
  "Act like a chicken until your next turn.",
  "Send a text to your crush saying 'Hey'.",
  "Let someone pour a glass of water on your head.",
  "Wear your clothes inside out for the rest of the game.",
  "Do the worm dance move.",
  "Talk in rhymes for the next three minutes.",
  "Let someone else style your hair in a ridiculous way.",
  "Pretend you're a news reporter and narrate everything happening in the room.",
  "Try to breakdance for 30 seconds.",
  "Put an ice cube down your shirt and let it melt.",
  "Let the person across from you send a text to anyone in your contacts.",
  "Balance a spoon on your nose for 10 seconds.",
  "Howl like a wolf at the moon (or ceiling).",
  "Make up a short story about the person to your left.",
- "Go to a neighbor's house and ask for a cup of sugar.",
  "Let the group create a short, silly dance for you to perform.",
  "Serenade the person to your right.",
  "Try to do a magic trick.",
  "Wear a piece of clothing as a hat for the next 10 minutes.",
  "Speak in only questions until your next turn.",
  "Do your best impression of another player in the room.",
  "Try to rap about the contents of the room.",
  "Let someone put makeup on you without a mirror.",
  "Build a small fort out of pillows and sit in it for one round.",
  "Tell a joke. If no one laughs, you have to do another dare.",
  "Let someone write a word on your forehead in marker.",
  "Act out a scene from your favorite movie.",
  "Go into another room and come back acting like a completely different person.",
  "Try to say the alphabet backward as fast as you can.",
  "For the next 5 minutes, everything you say must be a song lyric.",
  "Text your mom 'I'm running away to join the circus' and share her response."
];


export async function getRandomTruthOrDare(type: QuestionType): Promise<string> {
    if (type === 'truth') {
        const randomIndex = Math.floor(Math.random() * TRUTH_QUESTIONS.length);
        return TRUTH_QUESTIONS[randomIndex];
    } else {
        const randomIndex = Math.floor(Math.random() * DARES.length);
        return DARES[randomIndex];
    }
}
